//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace MasterControl.WSBot {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSBotSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class WSBot : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecebeDadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciaSessaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinalizaSessaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluiNovaMorteOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirLevelUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirLootOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirDetalheOperationCompleted;
        
        private System.Threading.SendOrPostCallback TesteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSBot() {
            this.Url = global::MasterControl.Properties.Settings.Default.MasterControl_WSBot_WSBot;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecebeDadosCompletedEventHandler RecebeDadosCompleted;
        
        /// <remarks/>
        public event IniciaSessaoCompletedEventHandler IniciaSessaoCompleted;
        
        /// <remarks/>
        public event FinalizaSessaoCompletedEventHandler FinalizaSessaoCompleted;
        
        /// <remarks/>
        public event IncluiNovaMorteCompletedEventHandler IncluiNovaMorteCompleted;
        
        /// <remarks/>
        public event IncluirLevelUpCompletedEventHandler IncluirLevelUpCompleted;
        
        /// <remarks/>
        public event IncluirLootCompletedEventHandler IncluirLootCompleted;
        
        /// <remarks/>
        public event IncluirDetalheCompletedEventHandler IncluirDetalheCompleted;
        
        /// <remarks/>
        public event TesteCompletedEventHandler TesteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecebeDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecebeDados(estDados datax, string key) {
            object[] results = this.Invoke("RecebeDados", new object[] {
                        datax,
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecebeDadosAsync(estDados datax, string key) {
            this.RecebeDadosAsync(datax, key, null);
        }
        
        /// <remarks/>
        public void RecebeDadosAsync(estDados datax, string key, object userState) {
            if ((this.RecebeDadosOperationCompleted == null)) {
                this.RecebeDadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecebeDadosOperationCompleted);
            }
            this.InvokeAsync("RecebeDados", new object[] {
                        datax,
                        key}, this.RecebeDadosOperationCompleted, userState);
        }
        
        private void OnRecebeDadosOperationCompleted(object arg) {
            if ((this.RecebeDadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecebeDadosCompleted(this, new RecebeDadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IniciaSessao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal IniciaSessao(estSessao s, string key) {
            object[] results = this.Invoke("IniciaSessao", new object[] {
                        s,
                        key});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void IniciaSessaoAsync(estSessao s, string key) {
            this.IniciaSessaoAsync(s, key, null);
        }
        
        /// <remarks/>
        public void IniciaSessaoAsync(estSessao s, string key, object userState) {
            if ((this.IniciaSessaoOperationCompleted == null)) {
                this.IniciaSessaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciaSessaoOperationCompleted);
            }
            this.InvokeAsync("IniciaSessao", new object[] {
                        s,
                        key}, this.IniciaSessaoOperationCompleted, userState);
        }
        
        private void OnIniciaSessaoOperationCompleted(object arg) {
            if ((this.IniciaSessaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciaSessaoCompleted(this, new IniciaSessaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FinalizaSessao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FinalizaSessao(estSessao s, System.DateTime d, string key) {
            this.Invoke("FinalizaSessao", new object[] {
                        s,
                        d,
                        key});
        }
        
        /// <remarks/>
        public void FinalizaSessaoAsync(estSessao s, System.DateTime d, string key) {
            this.FinalizaSessaoAsync(s, d, key, null);
        }
        
        /// <remarks/>
        public void FinalizaSessaoAsync(estSessao s, System.DateTime d, string key, object userState) {
            if ((this.FinalizaSessaoOperationCompleted == null)) {
                this.FinalizaSessaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinalizaSessaoOperationCompleted);
            }
            this.InvokeAsync("FinalizaSessao", new object[] {
                        s,
                        d,
                        key}, this.FinalizaSessaoOperationCompleted, userState);
        }
        
        private void OnFinalizaSessaoOperationCompleted(object arg) {
            if ((this.FinalizaSessaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinalizaSessaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluiNovaMorte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IncluiNovaMorte(estSessao s, estMorte m, string key) {
            this.Invoke("IncluiNovaMorte", new object[] {
                        s,
                        m,
                        key});
        }
        
        /// <remarks/>
        public void IncluiNovaMorteAsync(estSessao s, estMorte m, string key) {
            this.IncluiNovaMorteAsync(s, m, key, null);
        }
        
        /// <remarks/>
        public void IncluiNovaMorteAsync(estSessao s, estMorte m, string key, object userState) {
            if ((this.IncluiNovaMorteOperationCompleted == null)) {
                this.IncluiNovaMorteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluiNovaMorteOperationCompleted);
            }
            this.InvokeAsync("IncluiNovaMorte", new object[] {
                        s,
                        m,
                        key}, this.IncluiNovaMorteOperationCompleted, userState);
        }
        
        private void OnIncluiNovaMorteOperationCompleted(object arg) {
            if ((this.IncluiNovaMorteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluiNovaMorteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirLevelUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IncluirLevelUp(estSessao s, estLevelUp u, string key) {
            this.Invoke("IncluirLevelUp", new object[] {
                        s,
                        u,
                        key});
        }
        
        /// <remarks/>
        public void IncluirLevelUpAsync(estSessao s, estLevelUp u, string key) {
            this.IncluirLevelUpAsync(s, u, key, null);
        }
        
        /// <remarks/>
        public void IncluirLevelUpAsync(estSessao s, estLevelUp u, string key, object userState) {
            if ((this.IncluirLevelUpOperationCompleted == null)) {
                this.IncluirLevelUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirLevelUpOperationCompleted);
            }
            this.InvokeAsync("IncluirLevelUp", new object[] {
                        s,
                        u,
                        key}, this.IncluirLevelUpOperationCompleted, userState);
        }
        
        private void OnIncluirLevelUpOperationCompleted(object arg) {
            if ((this.IncluirLevelUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirLevelUpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirLoot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IncluirLoot(estSessao s, estLoot l, string key) {
            this.Invoke("IncluirLoot", new object[] {
                        s,
                        l,
                        key});
        }
        
        /// <remarks/>
        public void IncluirLootAsync(estSessao s, estLoot l, string key) {
            this.IncluirLootAsync(s, l, key, null);
        }
        
        /// <remarks/>
        public void IncluirLootAsync(estSessao s, estLoot l, string key, object userState) {
            if ((this.IncluirLootOperationCompleted == null)) {
                this.IncluirLootOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirLootOperationCompleted);
            }
            this.InvokeAsync("IncluirLoot", new object[] {
                        s,
                        l,
                        key}, this.IncluirLootOperationCompleted, userState);
        }
        
        private void OnIncluirLootOperationCompleted(object arg) {
            if ((this.IncluirLootCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirLootCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncluirDetalhe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IncluirDetalhe(estSessao s, estDetalhe d, string key) {
            this.Invoke("IncluirDetalhe", new object[] {
                        s,
                        d,
                        key});
        }
        
        /// <remarks/>
        public void IncluirDetalheAsync(estSessao s, estDetalhe d, string key) {
            this.IncluirDetalheAsync(s, d, key, null);
        }
        
        /// <remarks/>
        public void IncluirDetalheAsync(estSessao s, estDetalhe d, string key, object userState) {
            if ((this.IncluirDetalheOperationCompleted == null)) {
                this.IncluirDetalheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirDetalheOperationCompleted);
            }
            this.InvokeAsync("IncluirDetalhe", new object[] {
                        s,
                        d,
                        key}, this.IncluirDetalheOperationCompleted, userState);
        }
        
        private void OnIncluirDetalheOperationCompleted(object arg) {
            if ((this.IncluirDetalheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirDetalheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Teste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Morte Teste(string key) {
            object[] results = this.Invoke("Teste", new object[] {
                        key});
            return ((Morte)(results[0]));
        }
        
        /// <remarks/>
        public void TesteAsync(string key) {
            this.TesteAsync(key, null);
        }
        
        /// <remarks/>
        public void TesteAsync(string key, object userState) {
            if ((this.TesteOperationCompleted == null)) {
                this.TesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTesteOperationCompleted);
            }
            this.InvokeAsync("Teste", new object[] {
                        key}, this.TesteOperationCompleted, userState);
        }
        
        private void OnTesteOperationCompleted(object arg) {
            if ((this.TesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TesteCompleted(this, new TesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estDados {
        
        private string xpField;
        
        private string xp_neededField;
        
        private string nameField;
        
        /// <remarks/>
        public string xp {
            get {
                return this.xpField;
            }
            set {
                this.xpField = value;
            }
        }
        
        /// <remarks/>
        public string xp_needed {
            get {
                return this.xp_neededField;
            }
            set {
                this.xp_neededField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfSessao))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfSessao))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfSessao : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Morte))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Morte))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Morte : EntityObject {
        
        private decimal idField;
        
        private decimal id_sessaoField;
        
        private decimal mortesField;
        
        private decimal morteshoraField;
        
        private System.DateTime dtField;
        
        private string realZoneTextField;
        
        private string subZoneTextField;
        
        private EntityReferenceOfSessao sessaoReferenceField;
        
        /// <remarks/>
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public decimal id_sessao {
            get {
                return this.id_sessaoField;
            }
            set {
                this.id_sessaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal mortes {
            get {
                return this.mortesField;
            }
            set {
                this.mortesField = value;
            }
        }
        
        /// <remarks/>
        public decimal morteshora {
            get {
                return this.morteshoraField;
            }
            set {
                this.morteshoraField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public string RealZoneText {
            get {
                return this.realZoneTextField;
            }
            set {
                this.realZoneTextField = value;
            }
        }
        
        /// <remarks/>
        public string SubZoneText {
            get {
                return this.subZoneTextField;
            }
            set {
                this.subZoneTextField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfSessao SessaoReference {
            get {
                return this.sessaoReferenceField;
            }
            set {
                this.sessaoReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estDetalhe {
        
        private string runningtimeField;
        
        private string xpField;
        
        private string xp_neededField;
        
        private string xphField;
        
        private string timetolevelField;
        
        private string killsField;
        
        private string killshField;
        
        private string honorField;
        
        private string honorhField;
        
        private string goldField;
        
        private string bgwinField;
        
        private string bglostField;
        
        private string lvlField;
        
        private string realZoneTextField;
        
        private string subZoneTextField;
        
        /// <remarks/>
        public string runningtime {
            get {
                return this.runningtimeField;
            }
            set {
                this.runningtimeField = value;
            }
        }
        
        /// <remarks/>
        public string xp {
            get {
                return this.xpField;
            }
            set {
                this.xpField = value;
            }
        }
        
        /// <remarks/>
        public string xp_needed {
            get {
                return this.xp_neededField;
            }
            set {
                this.xp_neededField = value;
            }
        }
        
        /// <remarks/>
        public string xph {
            get {
                return this.xphField;
            }
            set {
                this.xphField = value;
            }
        }
        
        /// <remarks/>
        public string timetolevel {
            get {
                return this.timetolevelField;
            }
            set {
                this.timetolevelField = value;
            }
        }
        
        /// <remarks/>
        public string kills {
            get {
                return this.killsField;
            }
            set {
                this.killsField = value;
            }
        }
        
        /// <remarks/>
        public string killsh {
            get {
                return this.killshField;
            }
            set {
                this.killshField = value;
            }
        }
        
        /// <remarks/>
        public string honor {
            get {
                return this.honorField;
            }
            set {
                this.honorField = value;
            }
        }
        
        /// <remarks/>
        public string honorh {
            get {
                return this.honorhField;
            }
            set {
                this.honorhField = value;
            }
        }
        
        /// <remarks/>
        public string gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
            }
        }
        
        /// <remarks/>
        public string bgwin {
            get {
                return this.bgwinField;
            }
            set {
                this.bgwinField = value;
            }
        }
        
        /// <remarks/>
        public string bglost {
            get {
                return this.bglostField;
            }
            set {
                this.bglostField = value;
            }
        }
        
        /// <remarks/>
        public string lvl {
            get {
                return this.lvlField;
            }
            set {
                this.lvlField = value;
            }
        }
        
        /// <remarks/>
        public string RealZoneText {
            get {
                return this.realZoneTextField;
            }
            set {
                this.realZoneTextField = value;
            }
        }
        
        /// <remarks/>
        public string SubZoneText {
            get {
                return this.subZoneTextField;
            }
            set {
                this.subZoneTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estLoot {
        
        private System.DateTime dataField;
        
        private int idItemField;
        
        private int qtdField;
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int idItem {
            get {
                return this.idItemField;
            }
            set {
                this.idItemField = value;
            }
        }
        
        /// <remarks/>
        public int qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estLevelUp {
        
        private System.DateTime dataField;
        
        private int lvlField;
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int lvl {
            get {
                return this.lvlField;
            }
            set {
                this.lvlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estMorte {
        
        private int mortesField;
        
        private int morteshoraField;
        
        private System.DateTime dtField;
        
        private string realZoneTextField;
        
        private string subZoneTextField;
        
        /// <remarks/>
        public int mortes {
            get {
                return this.mortesField;
            }
            set {
                this.mortesField = value;
            }
        }
        
        /// <remarks/>
        public int morteshora {
            get {
                return this.morteshoraField;
            }
            set {
                this.morteshoraField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public string RealZoneText {
            get {
                return this.realZoneTextField;
            }
            set {
                this.realZoneTextField = value;
            }
        }
        
        /// <remarks/>
        public string SubZoneText {
            get {
                return this.subZoneTextField;
            }
            set {
                this.subZoneTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estSessao {
        
        private decimal idField;
        
        private System.DateTime dtInicioField;
        
        private string nomeField;
        
        private string botField;
        
        private string profileField;
        
        private string serverField;
        
        private string lvlField;
        
        private string versaoField;
        
        private string dirWoWField;
        
        /// <remarks/>
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtInicio {
            get {
                return this.dtInicioField;
            }
            set {
                this.dtInicioField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string bot {
            get {
                return this.botField;
            }
            set {
                this.botField = value;
            }
        }
        
        /// <remarks/>
        public string profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        public string server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public string lvl {
            get {
                return this.lvlField;
            }
            set {
                this.lvlField = value;
            }
        }
        
        /// <remarks/>
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        public string dirWoW {
            get {
                return this.dirWoWField;
            }
            set {
                this.dirWoWField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RecebeDadosCompletedEventHandler(object sender, RecebeDadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecebeDadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecebeDadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IniciaSessaoCompletedEventHandler(object sender, IniciaSessaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciaSessaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciaSessaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FinalizaSessaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IncluiNovaMorteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IncluirLevelUpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IncluirLootCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IncluirDetalheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TesteCompletedEventHandler(object sender, TesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Morte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Morte)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591