//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BotWoWModel", "FK_Morte_Sessao", "Sessao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServidorWeb.BD.Sessao), "Morte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServidorWeb.BD.Morte), true)]
[assembly: EdmRelationshipAttribute("BotWoWModel", "FK_levelup_Sessao", "Sessao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServidorWeb.BD.Sessao), "levelup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServidorWeb.BD.levelup), true)]
[assembly: EdmRelationshipAttribute("BotWoWModel", "FK_detalhes_Sessao", "Sessao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServidorWeb.BD.Sessao), "detalhe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServidorWeb.BD.detalhe), true)]
[assembly: EdmRelationshipAttribute("BotWoWModel", "FK_loot_Sessao", "Sessao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServidorWeb.BD.Sessao), "loot", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServidorWeb.BD.loot), true)]

#endregion

namespace ServidorWeb.BD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BotWoWEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BotWoWEntities object using the connection string found in the 'BotWoWEntities' section of the application configuration file.
        /// </summary>
        public BotWoWEntities() : base("name=BotWoWEntities", "BotWoWEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BotWoWEntities object.
        /// </summary>
        public BotWoWEntities(string connectionString) : base(connectionString, "BotWoWEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BotWoWEntities object.
        /// </summary>
        public BotWoWEntities(EntityConnection connection) : base(connection, "BotWoWEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sessao> Sessaos
        {
            get
            {
                if ((_Sessaos == null))
                {
                    _Sessaos = base.CreateObjectSet<Sessao>("Sessaos");
                }
                return _Sessaos;
            }
        }
        private ObjectSet<Sessao> _Sessaos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Morte> Mortes
        {
            get
            {
                if ((_Mortes == null))
                {
                    _Mortes = base.CreateObjectSet<Morte>("Mortes");
                }
                return _Mortes;
            }
        }
        private ObjectSet<Morte> _Mortes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<levelup> levelups
        {
            get
            {
                if ((_levelups == null))
                {
                    _levelups = base.CreateObjectSet<levelup>("levelups");
                }
                return _levelups;
            }
        }
        private ObjectSet<levelup> _levelups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<detalhe> detalhes
        {
            get
            {
                if ((_detalhes == null))
                {
                    _detalhes = base.CreateObjectSet<detalhe>("detalhes");
                }
                return _detalhes;
            }
        }
        private ObjectSet<detalhe> _detalhes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<loot> loots
        {
            get
            {
                if ((_loots == null))
                {
                    _loots = base.CreateObjectSet<loot>("loots");
                }
                return _loots;
            }
        }
        private ObjectSet<loot> _loots;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dado> dados
        {
            get
            {
                if ((_dados == null))
                {
                    _dados = base.CreateObjectSet<dado>("dados");
                }
                return _dados;
            }
        }
        private ObjectSet<dado> _dados;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Estoque> Estoques
        {
            get
            {
                if ((_Estoques == null))
                {
                    _Estoques = base.CreateObjectSet<Estoque>("Estoques");
                }
                return _Estoques;
            }
        }
        private ObjectSet<Estoque> _Estoques;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfiguracaoEstoque> ConfiguracaoEstoques
        {
            get
            {
                if ((_ConfiguracaoEstoques == null))
                {
                    _ConfiguracaoEstoques = base.CreateObjectSet<ConfiguracaoEstoque>("ConfiguracaoEstoques");
                }
                return _ConfiguracaoEstoques;
            }
        }
        private ObjectSet<ConfiguracaoEstoque> _ConfiguracaoEstoques;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SpellItem> SpellItems
        {
            get
            {
                if ((_SpellItems == null))
                {
                    _SpellItems = base.CreateObjectSet<SpellItem>("SpellItems");
                }
                return _SpellItems;
            }
        }
        private ObjectSet<SpellItem> _SpellItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessaos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessaos(Sessao sessao)
        {
            base.AddObject("Sessaos", sessao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mortes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMortes(Morte morte)
        {
            base.AddObject("Mortes", morte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the levelups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolevelups(levelup levelup)
        {
            base.AddObject("levelups", levelup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the detalhes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodetalhes(detalhe detalhe)
        {
            base.AddObject("detalhes", detalhe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the loots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToloots(loot loot)
        {
            base.AddObject("loots", loot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodados(dado dado)
        {
            base.AddObject("dados", dado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Estoques EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstoques(Estoque estoque)
        {
            base.AddObject("Estoques", estoque);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfiguracaoEstoques EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfiguracaoEstoques(ConfiguracaoEstoque configuracaoEstoque)
        {
            base.AddObject("ConfiguracaoEstoques", configuracaoEstoque);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SpellItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpellItems(SpellItem spellItem)
        {
            base.AddObject("SpellItems", spellItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="ConfiguracaoEstoque")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfiguracaoEstoque : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfiguracaoEstoque object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idItem">Initial value of the idItem property.</param>
        /// <param name="nomePersonagem">Initial value of the NomePersonagem property.</param>
        /// <param name="qtd">Initial value of the Qtd property.</param>
        public static ConfiguracaoEstoque CreateConfiguracaoEstoque(global::System.Decimal id, global::System.Decimal idItem, global::System.String nomePersonagem, global::System.Decimal qtd)
        {
            ConfiguracaoEstoque configuracaoEstoque = new ConfiguracaoEstoque();
            configuracaoEstoque.id = id;
            configuracaoEstoque.idItem = idItem;
            configuracaoEstoque.NomePersonagem = nomePersonagem;
            configuracaoEstoque.Qtd = qtd;
            return configuracaoEstoque;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal idItem
        {
            get
            {
                return _idItem;
            }
            set
            {
                OnidItemChanging(value);
                ReportPropertyChanging("idItem");
                _idItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idItem");
                OnidItemChanged();
            }
        }
        private global::System.Decimal _idItem;
        partial void OnidItemChanging(global::System.Decimal value);
        partial void OnidItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomePersonagem
        {
            get
            {
                return _NomePersonagem;
            }
            set
            {
                OnNomePersonagemChanging(value);
                ReportPropertyChanging("NomePersonagem");
                _NomePersonagem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomePersonagem");
                OnNomePersonagemChanged();
            }
        }
        private global::System.String _NomePersonagem;
        partial void OnNomePersonagemChanging(global::System.String value);
        partial void OnNomePersonagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Qtd
        {
            get
            {
                return _Qtd;
            }
            set
            {
                OnQtdChanging(value);
                ReportPropertyChanging("Qtd");
                _Qtd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qtd");
                OnQtdChanged();
            }
        }
        private global::System.Decimal _Qtd;
        partial void OnQtdChanging(global::System.Decimal value);
        partial void OnQtdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="dado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dado object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static dado Createdado(global::System.Decimal id)
        {
            dado dado = new dado();
            dado.id = id;
            return dado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xp
        {
            get
            {
                return _xp;
            }
            set
            {
                OnxpChanging(value);
                ReportPropertyChanging("xp");
                _xp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xp");
                OnxpChanged();
            }
        }
        private global::System.String _xp;
        partial void OnxpChanging(global::System.String value);
        partial void OnxpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xp_needed
        {
            get
            {
                return _xp_needed;
            }
            set
            {
                Onxp_neededChanging(value);
                ReportPropertyChanging("xp_needed");
                _xp_needed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xp_needed");
                Onxp_neededChanged();
            }
        }
        private global::System.String _xp_needed;
        partial void Onxp_neededChanging(global::System.String value);
        partial void Onxp_neededChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="detalhe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detalhe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new detalhe object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_sessao">Initial value of the id_sessao property.</param>
        /// <param name="runningtime">Initial value of the runningtime property.</param>
        public static detalhe Createdetalhe(global::System.Decimal id, global::System.Decimal id_sessao, global::System.Decimal runningtime)
        {
            detalhe detalhe = new detalhe();
            detalhe.id = id;
            detalhe.id_sessao = id_sessao;
            detalhe.runningtime = runningtime;
            return detalhe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_sessao
        {
            get
            {
                return _id_sessao;
            }
            set
            {
                Onid_sessaoChanging(value);
                ReportPropertyChanging("id_sessao");
                _id_sessao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_sessao");
                Onid_sessaoChanged();
            }
        }
        private global::System.Decimal _id_sessao;
        partial void Onid_sessaoChanging(global::System.Decimal value);
        partial void Onid_sessaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal runningtime
        {
            get
            {
                return _runningtime;
            }
            set
            {
                OnrunningtimeChanging(value);
                ReportPropertyChanging("runningtime");
                _runningtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("runningtime");
                OnrunningtimeChanged();
            }
        }
        private global::System.Decimal _runningtime;
        partial void OnrunningtimeChanging(global::System.Decimal value);
        partial void OnrunningtimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> xp
        {
            get
            {
                return _xp;
            }
            set
            {
                OnxpChanging(value);
                ReportPropertyChanging("xp");
                _xp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xp");
                OnxpChanged();
            }
        }
        private Nullable<global::System.Decimal> _xp;
        partial void OnxpChanging(Nullable<global::System.Decimal> value);
        partial void OnxpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> xp_needed
        {
            get
            {
                return _xp_needed;
            }
            set
            {
                Onxp_neededChanging(value);
                ReportPropertyChanging("xp_needed");
                _xp_needed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xp_needed");
                Onxp_neededChanged();
            }
        }
        private Nullable<global::System.Decimal> _xp_needed;
        partial void Onxp_neededChanging(Nullable<global::System.Decimal> value);
        partial void Onxp_neededChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> xph
        {
            get
            {
                return _xph;
            }
            set
            {
                OnxphChanging(value);
                ReportPropertyChanging("xph");
                _xph = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xph");
                OnxphChanged();
            }
        }
        private Nullable<global::System.Decimal> _xph;
        partial void OnxphChanging(Nullable<global::System.Decimal> value);
        partial void OnxphChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> timetolevel
        {
            get
            {
                return _timetolevel;
            }
            set
            {
                OntimetolevelChanging(value);
                ReportPropertyChanging("timetolevel");
                _timetolevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timetolevel");
                OntimetolevelChanged();
            }
        }
        private Nullable<global::System.Decimal> _timetolevel;
        partial void OntimetolevelChanging(Nullable<global::System.Decimal> value);
        partial void OntimetolevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kills
        {
            get
            {
                return _kills;
            }
            set
            {
                OnkillsChanging(value);
                ReportPropertyChanging("kills");
                _kills = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kills");
                OnkillsChanged();
            }
        }
        private Nullable<global::System.Decimal> _kills;
        partial void OnkillsChanging(Nullable<global::System.Decimal> value);
        partial void OnkillsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> killsh
        {
            get
            {
                return _killsh;
            }
            set
            {
                OnkillshChanging(value);
                ReportPropertyChanging("killsh");
                _killsh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("killsh");
                OnkillshChanged();
            }
        }
        private Nullable<global::System.Decimal> _killsh;
        partial void OnkillshChanging(Nullable<global::System.Decimal> value);
        partial void OnkillshChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> honor
        {
            get
            {
                return _honor;
            }
            set
            {
                OnhonorChanging(value);
                ReportPropertyChanging("honor");
                _honor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("honor");
                OnhonorChanged();
            }
        }
        private Nullable<global::System.Decimal> _honor;
        partial void OnhonorChanging(Nullable<global::System.Decimal> value);
        partial void OnhonorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> honorh
        {
            get
            {
                return _honorh;
            }
            set
            {
                OnhonorhChanging(value);
                ReportPropertyChanging("honorh");
                _honorh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("honorh");
                OnhonorhChanged();
            }
        }
        private Nullable<global::System.Decimal> _honorh;
        partial void OnhonorhChanging(Nullable<global::System.Decimal> value);
        partial void OnhonorhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> gold
        {
            get
            {
                return _gold;
            }
            set
            {
                OngoldChanging(value);
                ReportPropertyChanging("gold");
                _gold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gold");
                OngoldChanged();
            }
        }
        private Nullable<global::System.Decimal> _gold;
        partial void OngoldChanging(Nullable<global::System.Decimal> value);
        partial void OngoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> bgwin
        {
            get
            {
                return _bgwin;
            }
            set
            {
                OnbgwinChanging(value);
                ReportPropertyChanging("bgwin");
                _bgwin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bgwin");
                OnbgwinChanged();
            }
        }
        private Nullable<global::System.Decimal> _bgwin;
        partial void OnbgwinChanging(Nullable<global::System.Decimal> value);
        partial void OnbgwinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> bglost
        {
            get
            {
                return _bglost;
            }
            set
            {
                OnbglostChanging(value);
                ReportPropertyChanging("bglost");
                _bglost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bglost");
                OnbglostChanged();
            }
        }
        private Nullable<global::System.Decimal> _bglost;
        partial void OnbglostChanging(Nullable<global::System.Decimal> value);
        partial void OnbglostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lvl
        {
            get
            {
                return _lvl;
            }
            set
            {
                OnlvlChanging(value);
                ReportPropertyChanging("lvl");
                _lvl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lvl");
                OnlvlChanged();
            }
        }
        private Nullable<global::System.Decimal> _lvl;
        partial void OnlvlChanging(Nullable<global::System.Decimal> value);
        partial void OnlvlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealZoneText
        {
            get
            {
                return _RealZoneText;
            }
            set
            {
                OnRealZoneTextChanging(value);
                ReportPropertyChanging("RealZoneText");
                _RealZoneText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealZoneText");
                OnRealZoneTextChanged();
            }
        }
        private global::System.String _RealZoneText;
        partial void OnRealZoneTextChanging(global::System.String value);
        partial void OnRealZoneTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubZoneText
        {
            get
            {
                return _SubZoneText;
            }
            set
            {
                OnSubZoneTextChanging(value);
                ReportPropertyChanging("SubZoneText");
                _SubZoneText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubZoneText");
                OnSubZoneTextChanged();
            }
        }
        private global::System.String _SubZoneText;
        partial void OnSubZoneTextChanging(global::System.String value);
        partial void OnSubZoneTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_detalhes_Sessao", "Sessao")]
        public Sessao Sessao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_detalhes_Sessao", "Sessao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_detalhes_Sessao", "Sessao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessao> SessaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_detalhes_Sessao", "Sessao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessao>("BotWoWModel.FK_detalhes_Sessao", "Sessao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="Estoque")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estoque : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Estoque object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idItem">Initial value of the idItem property.</param>
        /// <param name="nomePersonagem">Initial value of the NomePersonagem property.</param>
        /// <param name="qtd">Initial value of the Qtd property.</param>
        public static Estoque CreateEstoque(global::System.Decimal id, global::System.Decimal idItem, global::System.String nomePersonagem, global::System.Decimal qtd)
        {
            Estoque estoque = new Estoque();
            estoque.id = id;
            estoque.idItem = idItem;
            estoque.NomePersonagem = nomePersonagem;
            estoque.Qtd = qtd;
            return estoque;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal idItem
        {
            get
            {
                return _idItem;
            }
            set
            {
                OnidItemChanging(value);
                ReportPropertyChanging("idItem");
                _idItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idItem");
                OnidItemChanged();
            }
        }
        private global::System.Decimal _idItem;
        partial void OnidItemChanging(global::System.Decimal value);
        partial void OnidItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomePersonagem
        {
            get
            {
                return _NomePersonagem;
            }
            set
            {
                OnNomePersonagemChanging(value);
                ReportPropertyChanging("NomePersonagem");
                _NomePersonagem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomePersonagem");
                OnNomePersonagemChanged();
            }
        }
        private global::System.String _NomePersonagem;
        partial void OnNomePersonagemChanging(global::System.String value);
        partial void OnNomePersonagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Qtd
        {
            get
            {
                return _Qtd;
            }
            set
            {
                OnQtdChanging(value);
                ReportPropertyChanging("Qtd");
                _Qtd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qtd");
                OnQtdChanged();
            }
        }
        private global::System.Decimal _Qtd;
        partial void OnQtdChanging(global::System.Decimal value);
        partial void OnQtdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtAtualizado
        {
            get
            {
                return _dtAtualizado;
            }
            set
            {
                OndtAtualizadoChanging(value);
                ReportPropertyChanging("dtAtualizado");
                _dtAtualizado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtAtualizado");
                OndtAtualizadoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtAtualizado;
        partial void OndtAtualizadoChanging(Nullable<global::System.DateTime> value);
        partial void OndtAtualizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtFabricado
        {
            get
            {
                return _dtFabricado;
            }
            set
            {
                OndtFabricadoChanging(value);
                ReportPropertyChanging("dtFabricado");
                _dtFabricado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtFabricado");
                OndtFabricadoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtFabricado;
        partial void OndtFabricadoChanging(Nullable<global::System.DateTime> value);
        partial void OndtFabricadoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="desc">Initial value of the Desc property.</param>
        public static Item CreateItem(global::System.Decimal id, global::System.String desc)
        {
            Item item = new Item();
            item.id = id;
            item.Desc = desc;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Desc
        {
            get
            {
                return _Desc;
            }
            set
            {
                OnDescChanging(value);
                ReportPropertyChanging("Desc");
                _Desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Desc");
                OnDescChanged();
            }
        }
        private global::System.String _Desc;
        partial void OnDescChanging(global::System.String value);
        partial void OnDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icon
        {
            get
            {
                return _icon;
            }
            set
            {
                OniconChanging(value);
                ReportPropertyChanging("icon");
                _icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icon");
                OniconChanged();
            }
        }
        private global::System.String _icon;
        partial void OniconChanging(global::System.String value);
        partial void OniconChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stackable
        {
            get
            {
                return _stackable;
            }
            set
            {
                OnstackableChanging(value);
                ReportPropertyChanging("stackable");
                _stackable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stackable");
                OnstackableChanged();
            }
        }
        private global::System.String _stackable;
        partial void OnstackableChanging(global::System.String value);
        partial void OnstackableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String itemBind
        {
            get
            {
                return _itemBind;
            }
            set
            {
                OnitemBindChanging(value);
                ReportPropertyChanging("itemBind");
                _itemBind = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("itemBind");
                OnitemBindChanged();
            }
        }
        private global::System.String _itemBind;
        partial void OnitemBindChanging(global::System.String value);
        partial void OnitemBindChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> buyPrice
        {
            get
            {
                return _buyPrice;
            }
            set
            {
                OnbuyPriceChanging(value);
                ReportPropertyChanging("buyPrice");
                _buyPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("buyPrice");
                OnbuyPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _buyPrice;
        partial void OnbuyPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnbuyPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> itemClass
        {
            get
            {
                return _itemClass;
            }
            set
            {
                OnitemClassChanging(value);
                ReportPropertyChanging("itemClass");
                _itemClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemClass");
                OnitemClassChanged();
            }
        }
        private Nullable<global::System.Decimal> _itemClass;
        partial void OnitemClassChanging(Nullable<global::System.Decimal> value);
        partial void OnitemClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> itemSubClass
        {
            get
            {
                return _itemSubClass;
            }
            set
            {
                OnitemSubClassChanging(value);
                ReportPropertyChanging("itemSubClass");
                _itemSubClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemSubClass");
                OnitemSubClassChanged();
            }
        }
        private Nullable<global::System.Decimal> _itemSubClass;
        partial void OnitemSubClassChanging(Nullable<global::System.Decimal> value);
        partial void OnitemSubClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> containerSlots
        {
            get
            {
                return _containerSlots;
            }
            set
            {
                OncontainerSlotsChanging(value);
                ReportPropertyChanging("containerSlots");
                _containerSlots = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("containerSlots");
                OncontainerSlotsChanged();
            }
        }
        private Nullable<global::System.Decimal> _containerSlots;
        partial void OncontainerSlotsChanging(Nullable<global::System.Decimal> value);
        partial void OncontainerSlotsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> inventoryType
        {
            get
            {
                return _inventoryType;
            }
            set
            {
                OninventoryTypeChanging(value);
                ReportPropertyChanging("inventoryType");
                _inventoryType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inventoryType");
                OninventoryTypeChanged();
            }
        }
        private Nullable<global::System.Decimal> _inventoryType;
        partial void OninventoryTypeChanging(Nullable<global::System.Decimal> value);
        partial void OninventoryTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> equippable
        {
            get
            {
                return _equippable;
            }
            set
            {
                OnequippableChanging(value);
                ReportPropertyChanging("equippable");
                _equippable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("equippable");
                OnequippableChanged();
            }
        }
        private Nullable<global::System.Decimal> _equippable;
        partial void OnequippableChanging(Nullable<global::System.Decimal> value);
        partial void OnequippableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> itemLevel
        {
            get
            {
                return _itemLevel;
            }
            set
            {
                OnitemLevelChanging(value);
                ReportPropertyChanging("itemLevel");
                _itemLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemLevel");
                OnitemLevelChanged();
            }
        }
        private Nullable<global::System.Decimal> _itemLevel;
        partial void OnitemLevelChanging(Nullable<global::System.Decimal> value);
        partial void OnitemLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> maxCount
        {
            get
            {
                return _maxCount;
            }
            set
            {
                OnmaxCountChanging(value);
                ReportPropertyChanging("maxCount");
                _maxCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maxCount");
                OnmaxCountChanged();
            }
        }
        private Nullable<global::System.Decimal> _maxCount;
        partial void OnmaxCountChanging(Nullable<global::System.Decimal> value);
        partial void OnmaxCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> maxDurability
        {
            get
            {
                return _maxDurability;
            }
            set
            {
                OnmaxDurabilityChanging(value);
                ReportPropertyChanging("maxDurability");
                _maxDurability = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maxDurability");
                OnmaxDurabilityChanged();
            }
        }
        private Nullable<global::System.Decimal> _maxDurability;
        partial void OnmaxDurabilityChanging(Nullable<global::System.Decimal> value);
        partial void OnmaxDurabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> minFactionId
        {
            get
            {
                return _minFactionId;
            }
            set
            {
                OnminFactionIdChanging(value);
                ReportPropertyChanging("minFactionId");
                _minFactionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("minFactionId");
                OnminFactionIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _minFactionId;
        partial void OnminFactionIdChanging(Nullable<global::System.Decimal> value);
        partial void OnminFactionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> minReputation
        {
            get
            {
                return _minReputation;
            }
            set
            {
                OnminReputationChanging(value);
                ReportPropertyChanging("minReputation");
                _minReputation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("minReputation");
                OnminReputationChanged();
            }
        }
        private Nullable<global::System.Decimal> _minReputation;
        partial void OnminReputationChanging(Nullable<global::System.Decimal> value);
        partial void OnminReputationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> quality
        {
            get
            {
                return _quality;
            }
            set
            {
                OnqualityChanging(value);
                ReportPropertyChanging("quality");
                _quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quality");
                OnqualityChanged();
            }
        }
        private Nullable<global::System.Decimal> _quality;
        partial void OnqualityChanging(Nullable<global::System.Decimal> value);
        partial void OnqualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ValorMinnaAH
        {
            get
            {
                return _ValorMinnaAH;
            }
            set
            {
                OnValorMinnaAHChanging(value);
                ReportPropertyChanging("ValorMinnaAH");
                _ValorMinnaAH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorMinnaAH");
                OnValorMinnaAHChanged();
            }
        }
        private Nullable<global::System.Decimal> _ValorMinnaAH;
        partial void OnValorMinnaAHChanging(Nullable<global::System.Decimal> value);
        partial void OnValorMinnaAHChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="levelup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class levelup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new levelup object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_sessao">Initial value of the id_sessao property.</param>
        /// <param name="dt">Initial value of the dt property.</param>
        /// <param name="lvl">Initial value of the lvl property.</param>
        public static levelup Createlevelup(global::System.Decimal id, global::System.Decimal id_sessao, global::System.DateTime dt, global::System.Decimal lvl)
        {
            levelup levelup = new levelup();
            levelup.id = id;
            levelup.id_sessao = id_sessao;
            levelup.dt = dt;
            levelup.lvl = lvl;
            return levelup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_sessao
        {
            get
            {
                return _id_sessao;
            }
            set
            {
                Onid_sessaoChanging(value);
                ReportPropertyChanging("id_sessao");
                _id_sessao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_sessao");
                Onid_sessaoChanged();
            }
        }
        private global::System.Decimal _id_sessao;
        partial void Onid_sessaoChanging(global::System.Decimal value);
        partial void Onid_sessaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt
        {
            get
            {
                return _dt;
            }
            set
            {
                OndtChanging(value);
                ReportPropertyChanging("dt");
                _dt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt");
                OndtChanged();
            }
        }
        private global::System.DateTime _dt;
        partial void OndtChanging(global::System.DateTime value);
        partial void OndtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal lvl
        {
            get
            {
                return _lvl;
            }
            set
            {
                OnlvlChanging(value);
                ReportPropertyChanging("lvl");
                _lvl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lvl");
                OnlvlChanged();
            }
        }
        private global::System.Decimal _lvl;
        partial void OnlvlChanging(global::System.Decimal value);
        partial void OnlvlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_levelup_Sessao", "Sessao")]
        public Sessao Sessao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_levelup_Sessao", "Sessao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_levelup_Sessao", "Sessao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessao> SessaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_levelup_Sessao", "Sessao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessao>("BotWoWModel.FK_levelup_Sessao", "Sessao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="loot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class loot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new loot object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_sessao">Initial value of the id_sessao property.</param>
        /// <param name="dt">Initial value of the dt property.</param>
        /// <param name="id_Item">Initial value of the id_Item property.</param>
        /// <param name="qtd">Initial value of the qtd property.</param>
        public static loot Createloot(global::System.Decimal id, global::System.Decimal id_sessao, global::System.DateTime dt, global::System.Decimal id_Item, global::System.Decimal qtd)
        {
            loot loot = new loot();
            loot.id = id;
            loot.id_sessao = id_sessao;
            loot.dt = dt;
            loot.id_Item = id_Item;
            loot.qtd = qtd;
            return loot;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_sessao
        {
            get
            {
                return _id_sessao;
            }
            set
            {
                Onid_sessaoChanging(value);
                ReportPropertyChanging("id_sessao");
                _id_sessao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_sessao");
                Onid_sessaoChanged();
            }
        }
        private global::System.Decimal _id_sessao;
        partial void Onid_sessaoChanging(global::System.Decimal value);
        partial void Onid_sessaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt
        {
            get
            {
                return _dt;
            }
            set
            {
                OndtChanging(value);
                ReportPropertyChanging("dt");
                _dt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt");
                OndtChanged();
            }
        }
        private global::System.DateTime _dt;
        partial void OndtChanging(global::System.DateTime value);
        partial void OndtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_Item
        {
            get
            {
                return _id_Item;
            }
            set
            {
                Onid_ItemChanging(value);
                ReportPropertyChanging("id_Item");
                _id_Item = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Item");
                Onid_ItemChanged();
            }
        }
        private global::System.Decimal _id_Item;
        partial void Onid_ItemChanging(global::System.Decimal value);
        partial void Onid_ItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal qtd
        {
            get
            {
                return _qtd;
            }
            set
            {
                OnqtdChanging(value);
                ReportPropertyChanging("qtd");
                _qtd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtd");
                OnqtdChanged();
            }
        }
        private global::System.Decimal _qtd;
        partial void OnqtdChanging(global::System.Decimal value);
        partial void OnqtdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_loot_Sessao", "Sessao")]
        public Sessao Sessao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_loot_Sessao", "Sessao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_loot_Sessao", "Sessao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessao> SessaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_loot_Sessao", "Sessao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessao>("BotWoWModel.FK_loot_Sessao", "Sessao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="Morte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Morte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Morte object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_sessao">Initial value of the id_sessao property.</param>
        /// <param name="mortes">Initial value of the mortes property.</param>
        /// <param name="morteshora">Initial value of the morteshora property.</param>
        /// <param name="dt">Initial value of the dt property.</param>
        public static Morte CreateMorte(global::System.Decimal id, global::System.Decimal id_sessao, global::System.Decimal mortes, global::System.Decimal morteshora, global::System.DateTime dt)
        {
            Morte morte = new Morte();
            morte.id = id;
            morte.id_sessao = id_sessao;
            morte.mortes = mortes;
            morte.morteshora = morteshora;
            morte.dt = dt;
            return morte;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_sessao
        {
            get
            {
                return _id_sessao;
            }
            set
            {
                Onid_sessaoChanging(value);
                ReportPropertyChanging("id_sessao");
                _id_sessao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_sessao");
                Onid_sessaoChanged();
            }
        }
        private global::System.Decimal _id_sessao;
        partial void Onid_sessaoChanging(global::System.Decimal value);
        partial void Onid_sessaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal mortes
        {
            get
            {
                return _mortes;
            }
            set
            {
                OnmortesChanging(value);
                ReportPropertyChanging("mortes");
                _mortes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mortes");
                OnmortesChanged();
            }
        }
        private global::System.Decimal _mortes;
        partial void OnmortesChanging(global::System.Decimal value);
        partial void OnmortesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal morteshora
        {
            get
            {
                return _morteshora;
            }
            set
            {
                OnmorteshoraChanging(value);
                ReportPropertyChanging("morteshora");
                _morteshora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("morteshora");
                OnmorteshoraChanged();
            }
        }
        private global::System.Decimal _morteshora;
        partial void OnmorteshoraChanging(global::System.Decimal value);
        partial void OnmorteshoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt
        {
            get
            {
                return _dt;
            }
            set
            {
                OndtChanging(value);
                ReportPropertyChanging("dt");
                _dt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt");
                OndtChanged();
            }
        }
        private global::System.DateTime _dt;
        partial void OndtChanging(global::System.DateTime value);
        partial void OndtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealZoneText
        {
            get
            {
                return _RealZoneText;
            }
            set
            {
                OnRealZoneTextChanging(value);
                ReportPropertyChanging("RealZoneText");
                _RealZoneText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealZoneText");
                OnRealZoneTextChanged();
            }
        }
        private global::System.String _RealZoneText;
        partial void OnRealZoneTextChanging(global::System.String value);
        partial void OnRealZoneTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubZoneText
        {
            get
            {
                return _SubZoneText;
            }
            set
            {
                OnSubZoneTextChanging(value);
                ReportPropertyChanging("SubZoneText");
                _SubZoneText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubZoneText");
                OnSubZoneTextChanged();
            }
        }
        private global::System.String _SubZoneText;
        partial void OnSubZoneTextChanging(global::System.String value);
        partial void OnSubZoneTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_Morte_Sessao", "Sessao")]
        public Sessao Sessao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_Morte_Sessao", "Sessao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_Morte_Sessao", "Sessao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessao> SessaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessao>("BotWoWModel.FK_Morte_Sessao", "Sessao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessao>("BotWoWModel.FK_Morte_Sessao", "Sessao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="Sessao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sessao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sessao object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="dt_inicio">Initial value of the dt_inicio property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="server">Initial value of the server property.</param>
        /// <param name="lvl">Initial value of the lvl property.</param>
        /// <param name="versao">Initial value of the versao property.</param>
        /// <param name="dirWoW">Initial value of the dirWoW property.</param>
        public static Sessao CreateSessao(global::System.Decimal id, global::System.DateTime dt_inicio, global::System.String nome, global::System.String server, global::System.String lvl, global::System.String versao, global::System.String dirWoW)
        {
            Sessao sessao = new Sessao();
            sessao.id = id;
            sessao.dt_inicio = dt_inicio;
            sessao.nome = nome;
            sessao.server = server;
            sessao.lvl = lvl;
            sessao.versao = versao;
            sessao.dirWoW = dirWoW;
            return sessao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt_inicio
        {
            get
            {
                return _dt_inicio;
            }
            set
            {
                Ondt_inicioChanging(value);
                ReportPropertyChanging("dt_inicio");
                _dt_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_inicio");
                Ondt_inicioChanged();
            }
        }
        private global::System.DateTime _dt_inicio;
        partial void Ondt_inicioChanging(global::System.DateTime value);
        partial void Ondt_inicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_fim
        {
            get
            {
                return _dt_fim;
            }
            set
            {
                Ondt_fimChanging(value);
                ReportPropertyChanging("dt_fim");
                _dt_fim = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_fim");
                Ondt_fimChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_fim;
        partial void Ondt_fimChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_fimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bot
        {
            get
            {
                return _bot;
            }
            set
            {
                OnbotChanging(value);
                ReportPropertyChanging("bot");
                _bot = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bot");
                OnbotChanged();
            }
        }
        private global::System.String _bot;
        partial void OnbotChanging(global::System.String value);
        partial void OnbotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String profile
        {
            get
            {
                return _profile;
            }
            set
            {
                OnprofileChanging(value);
                ReportPropertyChanging("profile");
                _profile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("profile");
                OnprofileChanged();
            }
        }
        private global::System.String _profile;
        partial void OnprofileChanging(global::System.String value);
        partial void OnprofileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String server
        {
            get
            {
                return _server;
            }
            set
            {
                OnserverChanging(value);
                ReportPropertyChanging("server");
                _server = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("server");
                OnserverChanged();
            }
        }
        private global::System.String _server;
        partial void OnserverChanging(global::System.String value);
        partial void OnserverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lvl
        {
            get
            {
                return _lvl;
            }
            set
            {
                OnlvlChanging(value);
                ReportPropertyChanging("lvl");
                _lvl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lvl");
                OnlvlChanged();
            }
        }
        private global::System.String _lvl;
        partial void OnlvlChanging(global::System.String value);
        partial void OnlvlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String versao
        {
            get
            {
                return _versao;
            }
            set
            {
                OnversaoChanging(value);
                ReportPropertyChanging("versao");
                _versao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("versao");
                OnversaoChanged();
            }
        }
        private global::System.String _versao;
        partial void OnversaoChanging(global::System.String value);
        partial void OnversaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dirWoW
        {
            get
            {
                return _dirWoW;
            }
            set
            {
                OndirWoWChanging(value);
                ReportPropertyChanging("dirWoW");
                _dirWoW = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dirWoW");
                OndirWoWChanged();
            }
        }
        private global::System.String _dirWoW;
        partial void OndirWoWChanging(global::System.String value);
        partial void OndirWoWChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_Morte_Sessao", "Morte")]
        public EntityCollection<Morte> Mortes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Morte>("BotWoWModel.FK_Morte_Sessao", "Morte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Morte>("BotWoWModel.FK_Morte_Sessao", "Morte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_levelup_Sessao", "levelup")]
        public EntityCollection<levelup> levelups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<levelup>("BotWoWModel.FK_levelup_Sessao", "levelup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<levelup>("BotWoWModel.FK_levelup_Sessao", "levelup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_detalhes_Sessao", "detalhe")]
        public EntityCollection<detalhe> detalhes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalhe>("BotWoWModel.FK_detalhes_Sessao", "detalhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalhe>("BotWoWModel.FK_detalhes_Sessao", "detalhe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BotWoWModel", "FK_loot_Sessao", "loot")]
        public EntityCollection<loot> loots
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<loot>("BotWoWModel.FK_loot_Sessao", "loot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<loot>("BotWoWModel.FK_loot_Sessao", "loot", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BotWoWModel", Name="SpellItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SpellItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SpellItem object.
        /// </summary>
        /// <param name="idSpell">Initial value of the idSpell property.</param>
        /// <param name="idItem">Initial value of the idItem property.</param>
        public static SpellItem CreateSpellItem(global::System.Decimal idSpell, global::System.Decimal idItem)
        {
            SpellItem spellItem = new SpellItem();
            spellItem.idSpell = idSpell;
            spellItem.idItem = idItem;
            return spellItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal idSpell
        {
            get
            {
                return _idSpell;
            }
            set
            {
                if (_idSpell != value)
                {
                    OnidSpellChanging(value);
                    ReportPropertyChanging("idSpell");
                    _idSpell = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idSpell");
                    OnidSpellChanged();
                }
            }
        }
        private global::System.Decimal _idSpell;
        partial void OnidSpellChanging(global::System.Decimal value);
        partial void OnidSpellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal idItem
        {
            get
            {
                return _idItem;
            }
            set
            {
                if (_idItem != value)
                {
                    OnidItemChanging(value);
                    ReportPropertyChanging("idItem");
                    _idItem = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idItem");
                    OnidItemChanged();
                }
            }
        }
        private global::System.Decimal _idItem;
        partial void OnidItemChanging(global::System.Decimal value);
        partial void OnidItemChanged();

        #endregion
    
    }

    #endregion
    
}
