//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NerdsaModel", "fk_venda_cliente", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Financeiro.cliente), "venda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.venda), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "fk_item_produto", "produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Financeiro.produto), "item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.item), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "fk_venda_item", "item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Financeiro.item), "venda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.venda), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "FK_Caixa_categoria", "categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Financeiro.categoria), "Caixa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.Caixa), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "FK_Caixa_TipoCaixa", "TipoCaixa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Financeiro.TipoCaixa), "Caixa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.Caixa), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "FK_LojaProduto_loja", "Loja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Financeiro.Loja), "LojaProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.LojaProduto), true)]
[assembly: EdmRelationshipAttribute("NerdsaModel", "FK_LojaProduto_produto", "produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Financeiro.produto), "LojaProduto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Financeiro.LojaProduto), true)]

#endregion

namespace Financeiro
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NerdEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NerdEntities object using the connection string found in the 'NerdEntities' section of the application configuration file.
        /// </summary>
        public NerdEntities() : base("name=NerdEntities", "NerdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NerdEntities object.
        /// </summary>
        public NerdEntities(string connectionString) : base(connectionString, "NerdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NerdEntities object.
        /// </summary>
        public NerdEntities(EntityConnection connection) : base(connection, "NerdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<categoria> categoria
        {
            get
            {
                if ((_categoria == null))
                {
                    _categoria = base.CreateObjectSet<categoria>("categoria");
                }
                return _categoria;
            }
        }
        private ObjectSet<categoria> _categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<item> item
        {
            get
            {
                if ((_item == null))
                {
                    _item = base.CreateObjectSet<item>("item");
                }
                return _item;
            }
        }
        private ObjectSet<item> _item;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<produto> produto
        {
            get
            {
                if ((_produto == null))
                {
                    _produto = base.CreateObjectSet<produto>("produto");
                }
                return _produto;
            }
        }
        private ObjectSet<produto> _produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<taxa> taxa
        {
            get
            {
                if ((_taxa == null))
                {
                    _taxa = base.CreateObjectSet<taxa>("taxa");
                }
                return _taxa;
            }
        }
        private ObjectSet<taxa> _taxa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<venda> venda
        {
            get
            {
                if ((_venda == null))
                {
                    _venda = base.CreateObjectSet<venda>("venda");
                }
                return _venda;
            }
        }
        private ObjectSet<venda> _venda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Caixa> Caixa
        {
            get
            {
                if ((_Caixa == null))
                {
                    _Caixa = base.CreateObjectSet<Caixa>("Caixa");
                }
                return _Caixa;
            }
        }
        private ObjectSet<Caixa> _Caixa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoCaixa> TipoCaixa
        {
            get
            {
                if ((_TipoCaixa == null))
                {
                    _TipoCaixa = base.CreateObjectSet<TipoCaixa>("TipoCaixa");
                }
                return _TipoCaixa;
            }
        }
        private ObjectSet<TipoCaixa> _TipoCaixa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Loja> Loja
        {
            get
            {
                if ((_Loja == null))
                {
                    _Loja = base.CreateObjectSet<Loja>("Loja");
                }
                return _Loja;
            }
        }
        private ObjectSet<Loja> _Loja;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LojaProduto> LojaProduto
        {
            get
            {
                if ((_LojaProduto == null))
                {
                    _LojaProduto = base.CreateObjectSet<LojaProduto>("LojaProduto");
                }
                return _LojaProduto;
            }
        }
        private ObjectSet<LojaProduto> _LojaProduto;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategoria(categoria categoria)
        {
            base.AddObject("categoria", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the item EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToitem(item item)
        {
            base.AddObject("item", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproduto(produto produto)
        {
            base.AddObject("produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the taxa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotaxa(taxa taxa)
        {
            base.AddObject("taxa", taxa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the venda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovenda(venda venda)
        {
            base.AddObject("venda", venda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Caixa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCaixa(Caixa caixa)
        {
            base.AddObject("Caixa", caixa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoCaixa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoCaixa(TipoCaixa tipoCaixa)
        {
            base.AddObject("TipoCaixa", tipoCaixa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Loja EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoja(Loja loja)
        {
            base.AddObject("Loja", loja);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LojaProduto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLojaProduto(LojaProduto lojaProduto)
        {
            base.AddObject("LojaProduto", lojaProduto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="Caixa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caixa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Caixa object.
        /// </summary>
        /// <param name="cod_Mov">Initial value of the Cod_Mov property.</param>
        public static Caixa CreateCaixa(global::System.Int32 cod_Mov)
        {
            Caixa caixa = new Caixa();
            caixa.Cod_Mov = cod_Mov;
            return caixa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Mov
        {
            get
            {
                return _Cod_Mov;
            }
            set
            {
                if (_Cod_Mov != value)
                {
                    OnCod_MovChanging(value);
                    ReportPropertyChanging("Cod_Mov");
                    _Cod_Mov = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Mov");
                    OnCod_MovChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Mov;
        partial void OnCod_MovChanging(global::System.Int32 value);
        partial void OnCod_MovChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cod_Caixa
        {
            get
            {
                return _Cod_Caixa;
            }
            set
            {
                OnCod_CaixaChanging(value);
                ReportPropertyChanging("Cod_Caixa");
                _Cod_Caixa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cod_Caixa");
                OnCod_CaixaChanged();
            }
        }
        private Nullable<global::System.Int32> _Cod_Caixa;
        partial void OnCod_CaixaChanging(Nullable<global::System.Int32> value);
        partial void OnCod_CaixaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cod_Categ
        {
            get
            {
                return _Cod_Categ;
            }
            set
            {
                OnCod_CategChanging(value);
                ReportPropertyChanging("Cod_Categ");
                _Cod_Categ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cod_Categ");
                OnCod_CategChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cod_Categ;
        partial void OnCod_CategChanging(Nullable<global::System.Decimal> value);
        partial void OnCod_CategChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Decimal> _valor;
        partial void OnvalorChanging(Nullable<global::System.Decimal> value);
        partial void OnvalorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_Caixa_categoria", "categoria")]
        public categoria categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categoria>("NerdsaModel.FK_Caixa_categoria", "categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categoria>("NerdsaModel.FK_Caixa_categoria", "categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<categoria> categoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categoria>("NerdsaModel.FK_Caixa_categoria", "categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<categoria>("NerdsaModel.FK_Caixa_categoria", "categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_Caixa_TipoCaixa", "TipoCaixa")]
        public TipoCaixa TipoCaixa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCaixa>("NerdsaModel.FK_Caixa_TipoCaixa", "TipoCaixa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCaixa>("NerdsaModel.FK_Caixa_TipoCaixa", "TipoCaixa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoCaixa> TipoCaixaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCaixa>("NerdsaModel.FK_Caixa_TipoCaixa", "TipoCaixa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoCaixa>("NerdsaModel.FK_Caixa_TipoCaixa", "TipoCaixa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new categoria object.
        /// </summary>
        /// <param name="cod_categ">Initial value of the cod_categ property.</param>
        public static categoria Createcategoria(global::System.Decimal cod_categ)
        {
            categoria categoria = new categoria();
            categoria.cod_categ = cod_categ;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cod_categ
        {
            get
            {
                return _cod_categ;
            }
            set
            {
                if (_cod_categ != value)
                {
                    Oncod_categChanging(value);
                    ReportPropertyChanging("cod_categ");
                    _cod_categ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_categ");
                    Oncod_categChanged();
                }
            }
        }
        private global::System.Decimal _cod_categ;
        partial void Oncod_categChanging(global::System.Decimal value);
        partial void Oncod_categChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descr_categ
        {
            get
            {
                return _descr_categ;
            }
            set
            {
                Ondescr_categChanging(value);
                ReportPropertyChanging("descr_categ");
                _descr_categ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descr_categ");
                Ondescr_categChanged();
            }
        }
        private global::System.String _descr_categ;
        partial void Ondescr_categChanging(global::System.String value);
        partial void Ondescr_categChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_Caixa_categoria", "Caixa")]
        public EntityCollection<Caixa> Caixa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Caixa>("NerdsaModel.FK_Caixa_categoria", "Caixa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Caixa>("NerdsaModel.FK_Caixa_categoria", "Caixa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cliente object.
        /// </summary>
        /// <param name="cod_cliente">Initial value of the cod_cliente property.</param>
        public static cliente Createcliente(global::System.Int32 cod_cliente)
        {
            cliente cliente = new cliente();
            cliente.cod_cliente = cod_cliente;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_cliente
        {
            get
            {
                return _cod_cliente;
            }
            set
            {
                if (_cod_cliente != value)
                {
                    Oncod_clienteChanging(value);
                    ReportPropertyChanging("cod_cliente");
                    _cod_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_cliente");
                    Oncod_clienteChanged();
                }
            }
        }
        private global::System.Int32 _cod_cliente;
        partial void Oncod_clienteChanging(global::System.Int32 value);
        partial void Oncod_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_venda_cliente", "venda")]
        public EntityCollection<venda> venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<venda>("NerdsaModel.fk_venda_cliente", "venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<venda>("NerdsaModel.fk_venda_cliente", "venda", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new item object.
        /// </summary>
        /// <param name="cod_item">Initial value of the cod_item property.</param>
        /// <param name="cod_produto">Initial value of the cod_produto property.</param>
        /// <param name="dt_compra">Initial value of the dt_compra property.</param>
        public static item Createitem(global::System.Int32 cod_item, global::System.Int32 cod_produto, global::System.DateTime dt_compra)
        {
            item item = new item();
            item.cod_item = cod_item;
            item.cod_produto = cod_produto;
            item.dt_compra = dt_compra;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_item
        {
            get
            {
                return _cod_item;
            }
            set
            {
                if (_cod_item != value)
                {
                    Oncod_itemChanging(value);
                    ReportPropertyChanging("cod_item");
                    _cod_item = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_item");
                    Oncod_itemChanged();
                }
            }
        }
        private global::System.Int32 _cod_item;
        partial void Oncod_itemChanging(global::System.Int32 value);
        partial void Oncod_itemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_produto
        {
            get
            {
                return _cod_produto;
            }
            set
            {
                Oncod_produtoChanging(value);
                ReportPropertyChanging("cod_produto");
                _cod_produto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cod_produto");
                Oncod_produtoChanged();
            }
        }
        private global::System.Int32 _cod_produto;
        partial void Oncod_produtoChanging(global::System.Int32 value);
        partial void Oncod_produtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt_compra
        {
            get
            {
                return _dt_compra;
            }
            set
            {
                Ondt_compraChanging(value);
                ReportPropertyChanging("dt_compra");
                _dt_compra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_compra");
                Ondt_compraChanged();
            }
        }
        private global::System.DateTime _dt_compra;
        partial void Ondt_compraChanging(global::System.DateTime value);
        partial void Ondt_compraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> preco
        {
            get
            {
                return _preco;
            }
            set
            {
                OnprecoChanging(value);
                ReportPropertyChanging("preco");
                _preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("preco");
                OnprecoChanged();
            }
        }
        private Nullable<global::System.Single> _preco;
        partial void OnprecoChanging(Nullable<global::System.Single> value);
        partial void OnprecoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_item_produto", "produto")]
        public produto produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.fk_item_produto", "produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.fk_item_produto", "produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<produto> produtoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.fk_item_produto", "produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<produto>("NerdsaModel.fk_item_produto", "produto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_venda_item", "venda")]
        public EntityCollection<venda> venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<venda>("NerdsaModel.fk_venda_item", "venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<venda>("NerdsaModel.fk_venda_item", "venda", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="Loja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Loja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Loja object.
        /// </summary>
        /// <param name="cod_Loja">Initial value of the Cod_Loja property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Loja CreateLoja(global::System.Int32 cod_Loja, global::System.String nome)
        {
            Loja loja = new Loja();
            loja.Cod_Loja = cod_Loja;
            loja.Nome = nome;
            return loja;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Loja
        {
            get
            {
                return _Cod_Loja;
            }
            set
            {
                if (_Cod_Loja != value)
                {
                    OnCod_LojaChanging(value);
                    ReportPropertyChanging("Cod_Loja");
                    _Cod_Loja = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Loja");
                    OnCod_LojaChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Loja;
        partial void OnCod_LojaChanging(global::System.Int32 value);
        partial void OnCod_LojaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> tarifa
        {
            get
            {
                return _tarifa;
            }
            set
            {
                OntarifaChanging(value);
                ReportPropertyChanging("tarifa");
                _tarifa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tarifa");
                OntarifaChanged();
            }
        }
        private Nullable<global::System.Decimal> _tarifa;
        partial void OntarifaChanging(Nullable<global::System.Decimal> value);
        partial void OntarifaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_LojaProduto_loja", "LojaProduto")]
        public EntityCollection<LojaProduto> LojaProduto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LojaProduto>("NerdsaModel.FK_LojaProduto_loja", "LojaProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LojaProduto>("NerdsaModel.FK_LojaProduto_loja", "LojaProduto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="LojaProduto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LojaProduto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LojaProduto object.
        /// </summary>
        /// <param name="cod_Produto">Initial value of the Cod_Produto property.</param>
        /// <param name="cod_Loja">Initial value of the Cod_Loja property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        public static LojaProduto CreateLojaProduto(global::System.Int32 cod_Produto, global::System.Int32 cod_Loja, global::System.Decimal preco)
        {
            LojaProduto lojaProduto = new LojaProduto();
            lojaProduto.Cod_Produto = cod_Produto;
            lojaProduto.Cod_Loja = cod_Loja;
            lojaProduto.Preco = preco;
            return lojaProduto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Produto
        {
            get
            {
                return _Cod_Produto;
            }
            set
            {
                if (_Cod_Produto != value)
                {
                    OnCod_ProdutoChanging(value);
                    ReportPropertyChanging("Cod_Produto");
                    _Cod_Produto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Produto");
                    OnCod_ProdutoChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Produto;
        partial void OnCod_ProdutoChanging(global::System.Int32 value);
        partial void OnCod_ProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Loja
        {
            get
            {
                return _Cod_Loja;
            }
            set
            {
                if (_Cod_Loja != value)
                {
                    OnCod_LojaChanging(value);
                    ReportPropertyChanging("Cod_Loja");
                    _Cod_Loja = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Loja");
                    OnCod_LojaChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Loja;
        partial void OnCod_LojaChanging(global::System.Int32 value);
        partial void OnCod_LojaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_LojaProduto_loja", "Loja")]
        public Loja Loja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("NerdsaModel.FK_LojaProduto_loja", "Loja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("NerdsaModel.FK_LojaProduto_loja", "Loja").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loja> LojaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("NerdsaModel.FK_LojaProduto_loja", "Loja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loja>("NerdsaModel.FK_LojaProduto_loja", "Loja", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_LojaProduto_produto", "produto")]
        public produto produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.FK_LojaProduto_produto", "produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.FK_LojaProduto_produto", "produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<produto> produtoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<produto>("NerdsaModel.FK_LojaProduto_produto", "produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<produto>("NerdsaModel.FK_LojaProduto_produto", "produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new produto object.
        /// </summary>
        /// <param name="cod_produto">Initial value of the cod_produto property.</param>
        public static produto Createproduto(global::System.Int32 cod_produto)
        {
            produto produto = new produto();
            produto.cod_produto = cod_produto;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_produto
        {
            get
            {
                return _cod_produto;
            }
            set
            {
                if (_cod_produto != value)
                {
                    Oncod_produtoChanging(value);
                    ReportPropertyChanging("cod_produto");
                    _cod_produto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_produto");
                    Oncod_produtoChanged();
                }
            }
        }
        private global::System.Int32 _cod_produto;
        partial void Oncod_produtoChanging(global::System.Int32 value);
        partial void Oncod_produtoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantidade
        {
            get
            {
                return _quantidade;
            }
            set
            {
                OnquantidadeChanging(value);
                ReportPropertyChanging("quantidade");
                _quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantidade");
                OnquantidadeChanged();
            }
        }
        private Nullable<global::System.Int32> _quantidade;
        partial void OnquantidadeChanging(Nullable<global::System.Int32> value);
        partial void OnquantidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_item_produto", "item")]
        public EntityCollection<item> item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<item>("NerdsaModel.fk_item_produto", "item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<item>("NerdsaModel.fk_item_produto", "item", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_LojaProduto_produto", "LojaProduto")]
        public EntityCollection<LojaProduto> LojaProduto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LojaProduto>("NerdsaModel.FK_LojaProduto_produto", "LojaProduto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LojaProduto>("NerdsaModel.FK_LojaProduto_produto", "LojaProduto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="taxa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class taxa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new taxa object.
        /// </summary>
        /// <param name="preco_kg">Initial value of the preco_kg property.</param>
        /// <param name="icms">Initial value of the icms property.</param>
        /// <param name="paypal">Initial value of the paypal property.</param>
        /// <param name="dARJ">Initial value of the DARJ property.</param>
        public static taxa Createtaxa(global::System.Single preco_kg, global::System.Single icms, global::System.Single paypal, global::System.Single dARJ)
        {
            taxa taxa = new taxa();
            taxa.preco_kg = preco_kg;
            taxa.icms = icms;
            taxa.paypal = paypal;
            taxa.DARJ = dARJ;
            return taxa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single preco_kg
        {
            get
            {
                return _preco_kg;
            }
            set
            {
                if (_preco_kg != value)
                {
                    Onpreco_kgChanging(value);
                    ReportPropertyChanging("preco_kg");
                    _preco_kg = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("preco_kg");
                    Onpreco_kgChanged();
                }
            }
        }
        private global::System.Single _preco_kg;
        partial void Onpreco_kgChanging(global::System.Single value);
        partial void Onpreco_kgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single icms
        {
            get
            {
                return _icms;
            }
            set
            {
                if (_icms != value)
                {
                    OnicmsChanging(value);
                    ReportPropertyChanging("icms");
                    _icms = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("icms");
                    OnicmsChanged();
                }
            }
        }
        private global::System.Single _icms;
        partial void OnicmsChanging(global::System.Single value);
        partial void OnicmsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single paypal
        {
            get
            {
                return _paypal;
            }
            set
            {
                if (_paypal != value)
                {
                    OnpaypalChanging(value);
                    ReportPropertyChanging("paypal");
                    _paypal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("paypal");
                    OnpaypalChanged();
                }
            }
        }
        private global::System.Single _paypal;
        partial void OnpaypalChanging(global::System.Single value);
        partial void OnpaypalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single DARJ
        {
            get
            {
                return _DARJ;
            }
            set
            {
                if (_DARJ != value)
                {
                    OnDARJChanging(value);
                    ReportPropertyChanging("DARJ");
                    _DARJ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DARJ");
                    OnDARJChanged();
                }
            }
        }
        private global::System.Single _DARJ;
        partial void OnDARJChanging(global::System.Single value);
        partial void OnDARJChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="TipoCaixa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoCaixa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoCaixa object.
        /// </summary>
        /// <param name="cod_Caixa">Initial value of the Cod_Caixa property.</param>
        public static TipoCaixa CreateTipoCaixa(global::System.Int32 cod_Caixa)
        {
            TipoCaixa tipoCaixa = new TipoCaixa();
            tipoCaixa.Cod_Caixa = cod_Caixa;
            return tipoCaixa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Caixa
        {
            get
            {
                return _Cod_Caixa;
            }
            set
            {
                if (_Cod_Caixa != value)
                {
                    OnCod_CaixaChanging(value);
                    ReportPropertyChanging("Cod_Caixa");
                    _Cod_Caixa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Caixa");
                    OnCod_CaixaChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Caixa;
        partial void OnCod_CaixaChanging(global::System.Int32 value);
        partial void OnCod_CaixaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Desc_Caixa
        {
            get
            {
                return _Desc_Caixa;
            }
            set
            {
                OnDesc_CaixaChanging(value);
                ReportPropertyChanging("Desc_Caixa");
                _Desc_Caixa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Desc_Caixa");
                OnDesc_CaixaChanged();
            }
        }
        private global::System.String _Desc_Caixa;
        partial void OnDesc_CaixaChanging(global::System.String value);
        partial void OnDesc_CaixaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "FK_Caixa_TipoCaixa", "Caixa")]
        public EntityCollection<Caixa> Caixa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Caixa>("NerdsaModel.FK_Caixa_TipoCaixa", "Caixa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Caixa>("NerdsaModel.FK_Caixa_TipoCaixa", "Caixa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NerdsaModel", Name="venda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class venda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new venda object.
        /// </summary>
        /// <param name="cod_venda">Initial value of the cod_venda property.</param>
        /// <param name="cod_item">Initial value of the cod_item property.</param>
        public static venda Createvenda(global::System.Int32 cod_venda, global::System.Int32 cod_item)
        {
            venda venda = new venda();
            venda.cod_venda = cod_venda;
            venda.cod_item = cod_item;
            return venda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_venda
        {
            get
            {
                return _cod_venda;
            }
            set
            {
                if (_cod_venda != value)
                {
                    Oncod_vendaChanging(value);
                    ReportPropertyChanging("cod_venda");
                    _cod_venda = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_venda");
                    Oncod_vendaChanged();
                }
            }
        }
        private global::System.Int32 _cod_venda;
        partial void Oncod_vendaChanging(global::System.Int32 value);
        partial void Oncod_vendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cod_item
        {
            get
            {
                return _cod_item;
            }
            set
            {
                if (_cod_item != value)
                {
                    Oncod_itemChanging(value);
                    ReportPropertyChanging("cod_item");
                    _cod_item = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cod_item");
                    Oncod_itemChanged();
                }
            }
        }
        private global::System.Int32 _cod_item;
        partial void Oncod_itemChanging(global::System.Int32 value);
        partial void Oncod_itemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cod_cliente
        {
            get
            {
                return _cod_cliente;
            }
            set
            {
                Oncod_clienteChanging(value);
                ReportPropertyChanging("cod_cliente");
                _cod_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cod_cliente");
                Oncod_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _cod_cliente;
        partial void Oncod_clienteChanging(Nullable<global::System.Int32> value);
        partial void Oncod_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_venda
        {
            get
            {
                return _dt_venda;
            }
            set
            {
                Ondt_vendaChanging(value);
                ReportPropertyChanging("dt_venda");
                _dt_venda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_venda");
                Ondt_vendaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_venda;
        partial void Ondt_vendaChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_vendaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_venda_cliente", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("NerdsaModel.fk_venda_cliente", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("NerdsaModel.fk_venda_cliente", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("NerdsaModel.fk_venda_cliente", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("NerdsaModel.fk_venda_cliente", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NerdsaModel", "fk_venda_item", "item")]
        public item item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item>("NerdsaModel.fk_venda_item", "item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item>("NerdsaModel.fk_venda_item", "item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<item> itemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<item>("NerdsaModel.fk_venda_item", "item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<item>("NerdsaModel.fk_venda_item", "item", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
