//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace ServidorWeb.WSNerdMoney {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NerdMoneySoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(produto[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class NerdMoney : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaTodosProdutosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluiProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback incluiLojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaLojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaTodasLojasOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraLojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluiLojasOperationCompleted;
        
        private System.Threading.SendOrPostCallback incluiProdutoLojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaProdutosLojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluiLojaProdutosOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraLojaProdutosOperationCompleted;
        
        private System.Threading.SendOrPostCallback realizaVendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback refactorProdutoNovoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DepositoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback incluiTipoCaixaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saldoCaixaOperationCompleted;
        
        private System.Threading.SendOrPostCallback incluiTipoCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback incluiClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback alteraClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluiclienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaTodosClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NerdMoney() {
            this.Url = global::ServidorWeb.Properties.Settings.Default.ServidorWeb_WSTIAGO_NerdMoney;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaTodosProdutosCompletedEventHandler consultaTodosProdutosCompleted;
        
        /// <remarks/>
        public event consultaProdutoCompletedEventHandler consultaProdutoCompleted;
        
        /// <remarks/>
        public event alteraProdutoCompletedEventHandler alteraProdutoCompleted;
        
        /// <remarks/>
        public event excluiProdutoCompletedEventHandler excluiProdutoCompleted;
        
        /// <remarks/>
        public event incluiLojaCompletedEventHandler incluiLojaCompleted;
        
        /// <remarks/>
        public event consultaLojaCompletedEventHandler consultaLojaCompleted;
        
        /// <remarks/>
        public event consultaTodasLojasCompletedEventHandler consultaTodasLojasCompleted;
        
        /// <remarks/>
        public event alteraLojaCompletedEventHandler alteraLojaCompleted;
        
        /// <remarks/>
        public event excluiLojasCompletedEventHandler excluiLojasCompleted;
        
        /// <remarks/>
        public event incluiProdutoLojaCompletedEventHandler incluiProdutoLojaCompleted;
        
        /// <remarks/>
        public event consultaProdutosLojaCompletedEventHandler consultaProdutosLojaCompleted;
        
        /// <remarks/>
        public event excluiLojaProdutosCompletedEventHandler excluiLojaProdutosCompleted;
        
        /// <remarks/>
        public event alteraLojaProdutosCompletedEventHandler alteraLojaProdutosCompleted;
        
        /// <remarks/>
        public event realizaVendaCompletedEventHandler realizaVendaCompleted;
        
        /// <remarks/>
        public event refactorProdutoNovoCompletedEventHandler refactorProdutoNovoCompleted;
        
        /// <remarks/>
        public event DepositoCompletedEventHandler DepositoCompleted;
        
        /// <remarks/>
        public event SaqueCompletedEventHandler SaqueCompleted;
        
        /// <remarks/>
        public event incluiTipoCaixaCompletedEventHandler incluiTipoCaixaCompleted;
        
        /// <remarks/>
        public event SaldoCompletedEventHandler SaldoCompleted;
        
        /// <remarks/>
        public event saldoCaixaCompletedEventHandler saldoCaixaCompleted;
        
        /// <remarks/>
        public event incluiTipoCategoriaCompletedEventHandler incluiTipoCategoriaCompleted;
        
        /// <remarks/>
        public event incluiClienteCompletedEventHandler incluiClienteCompleted;
        
        /// <remarks/>
        public event alteraClienteCompletedEventHandler alteraClienteCompleted;
        
        /// <remarks/>
        public event excluiclienteCompletedEventHandler excluiclienteCompleted;
        
        /// <remarks/>
        public event consultaClienteCompletedEventHandler consultaClienteCompleted;
        
        /// <remarks/>
        public event consultaTodosClienteCompletedEventHandler consultaTodosClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaTodosProdutos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public produto[] consultaTodosProdutos() {
            object[] results = this.Invoke("consultaTodosProdutos", new object[0]);
            return ((produto[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaTodosProdutosAsync() {
            this.consultaTodosProdutosAsync(null);
        }
        
        /// <remarks/>
        public void consultaTodosProdutosAsync(object userState) {
            if ((this.consultaTodosProdutosOperationCompleted == null)) {
                this.consultaTodosProdutosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaTodosProdutosOperationCompleted);
            }
            this.InvokeAsync("consultaTodosProdutos", new object[0], this.consultaTodosProdutosOperationCompleted, userState);
        }
        
        private void OnconsultaTodosProdutosOperationCompleted(object arg) {
            if ((this.consultaTodosProdutosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaTodosProdutosCompleted(this, new consultaTodosProdutosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public produto consultaProduto(int codProduto) {
            object[] results = this.Invoke("consultaProduto", new object[] {
                        codProduto});
            return ((produto)(results[0]));
        }
        
        /// <remarks/>
        public void consultaProdutoAsync(int codProduto) {
            this.consultaProdutoAsync(codProduto, null);
        }
        
        /// <remarks/>
        public void consultaProdutoAsync(int codProduto, object userState) {
            if ((this.consultaProdutoOperationCompleted == null)) {
                this.consultaProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaProdutoOperationCompleted);
            }
            this.InvokeAsync("consultaProduto", new object[] {
                        codProduto}, this.consultaProdutoOperationCompleted, userState);
        }
        
        private void OnconsultaProdutoOperationCompleted(object arg) {
            if ((this.consultaProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaProdutoCompleted(this, new consultaProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alteraProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alteraProduto(int codProduto, int quant, string nome) {
            this.Invoke("alteraProduto", new object[] {
                        codProduto,
                        quant,
                        nome});
        }
        
        /// <remarks/>
        public void alteraProdutoAsync(int codProduto, int quant, string nome) {
            this.alteraProdutoAsync(codProduto, quant, nome, null);
        }
        
        /// <remarks/>
        public void alteraProdutoAsync(int codProduto, int quant, string nome, object userState) {
            if ((this.alteraProdutoOperationCompleted == null)) {
                this.alteraProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraProdutoOperationCompleted);
            }
            this.InvokeAsync("alteraProduto", new object[] {
                        codProduto,
                        quant,
                        nome}, this.alteraProdutoOperationCompleted, userState);
        }
        
        private void OnalteraProdutoOperationCompleted(object arg) {
            if ((this.alteraProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluiProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluiProduto(int codProduto) {
            this.Invoke("excluiProduto", new object[] {
                        codProduto});
        }
        
        /// <remarks/>
        public void excluiProdutoAsync(int codProduto) {
            this.excluiProdutoAsync(codProduto, null);
        }
        
        /// <remarks/>
        public void excluiProdutoAsync(int codProduto, object userState) {
            if ((this.excluiProdutoOperationCompleted == null)) {
                this.excluiProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluiProdutoOperationCompleted);
            }
            this.InvokeAsync("excluiProduto", new object[] {
                        codProduto}, this.excluiProdutoOperationCompleted, userState);
        }
        
        private void OnexcluiProdutoOperationCompleted(object arg) {
            if ((this.excluiProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluiProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/incluiLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void incluiLoja(double tarifa, string nome) {
            this.Invoke("incluiLoja", new object[] {
                        tarifa,
                        nome});
        }
        
        /// <remarks/>
        public void incluiLojaAsync(double tarifa, string nome) {
            this.incluiLojaAsync(tarifa, nome, null);
        }
        
        /// <remarks/>
        public void incluiLojaAsync(double tarifa, string nome, object userState) {
            if ((this.incluiLojaOperationCompleted == null)) {
                this.incluiLojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincluiLojaOperationCompleted);
            }
            this.InvokeAsync("incluiLoja", new object[] {
                        tarifa,
                        nome}, this.incluiLojaOperationCompleted, userState);
        }
        
        private void OnincluiLojaOperationCompleted(object arg) {
            if ((this.incluiLojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incluiLojaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Loja[] consultaLoja(int codLoja) {
            object[] results = this.Invoke("consultaLoja", new object[] {
                        codLoja});
            return ((Loja[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaLojaAsync(int codLoja) {
            this.consultaLojaAsync(codLoja, null);
        }
        
        /// <remarks/>
        public void consultaLojaAsync(int codLoja, object userState) {
            if ((this.consultaLojaOperationCompleted == null)) {
                this.consultaLojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaLojaOperationCompleted);
            }
            this.InvokeAsync("consultaLoja", new object[] {
                        codLoja}, this.consultaLojaOperationCompleted, userState);
        }
        
        private void OnconsultaLojaOperationCompleted(object arg) {
            if ((this.consultaLojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaLojaCompleted(this, new consultaLojaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaTodasLojas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Loja[] consultaTodasLojas() {
            object[] results = this.Invoke("consultaTodasLojas", new object[0]);
            return ((Loja[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaTodasLojasAsync() {
            this.consultaTodasLojasAsync(null);
        }
        
        /// <remarks/>
        public void consultaTodasLojasAsync(object userState) {
            if ((this.consultaTodasLojasOperationCompleted == null)) {
                this.consultaTodasLojasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaTodasLojasOperationCompleted);
            }
            this.InvokeAsync("consultaTodasLojas", new object[0], this.consultaTodasLojasOperationCompleted, userState);
        }
        
        private void OnconsultaTodasLojasOperationCompleted(object arg) {
            if ((this.consultaTodasLojasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaTodasLojasCompleted(this, new consultaTodasLojasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alteraLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alteraLoja(int codLoja, double tarifa, string nome) {
            this.Invoke("alteraLoja", new object[] {
                        codLoja,
                        tarifa,
                        nome});
        }
        
        /// <remarks/>
        public void alteraLojaAsync(int codLoja, double tarifa, string nome) {
            this.alteraLojaAsync(codLoja, tarifa, nome, null);
        }
        
        /// <remarks/>
        public void alteraLojaAsync(int codLoja, double tarifa, string nome, object userState) {
            if ((this.alteraLojaOperationCompleted == null)) {
                this.alteraLojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraLojaOperationCompleted);
            }
            this.InvokeAsync("alteraLoja", new object[] {
                        codLoja,
                        tarifa,
                        nome}, this.alteraLojaOperationCompleted, userState);
        }
        
        private void OnalteraLojaOperationCompleted(object arg) {
            if ((this.alteraLojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraLojaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluiLojas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluiLojas(int codLoja) {
            this.Invoke("excluiLojas", new object[] {
                        codLoja});
        }
        
        /// <remarks/>
        public void excluiLojasAsync(int codLoja) {
            this.excluiLojasAsync(codLoja, null);
        }
        
        /// <remarks/>
        public void excluiLojasAsync(int codLoja, object userState) {
            if ((this.excluiLojasOperationCompleted == null)) {
                this.excluiLojasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluiLojasOperationCompleted);
            }
            this.InvokeAsync("excluiLojas", new object[] {
                        codLoja}, this.excluiLojasOperationCompleted, userState);
        }
        
        private void OnexcluiLojasOperationCompleted(object arg) {
            if ((this.excluiLojasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluiLojasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/incluiProdutoLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void incluiProdutoLoja(int codLoja, int codProduto, double preco) {
            this.Invoke("incluiProdutoLoja", new object[] {
                        codLoja,
                        codProduto,
                        preco});
        }
        
        /// <remarks/>
        public void incluiProdutoLojaAsync(int codLoja, int codProduto, double preco) {
            this.incluiProdutoLojaAsync(codLoja, codProduto, preco, null);
        }
        
        /// <remarks/>
        public void incluiProdutoLojaAsync(int codLoja, int codProduto, double preco, object userState) {
            if ((this.incluiProdutoLojaOperationCompleted == null)) {
                this.incluiProdutoLojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincluiProdutoLojaOperationCompleted);
            }
            this.InvokeAsync("incluiProdutoLoja", new object[] {
                        codLoja,
                        codProduto,
                        preco}, this.incluiProdutoLojaOperationCompleted, userState);
        }
        
        private void OnincluiProdutoLojaOperationCompleted(object arg) {
            if ((this.incluiProdutoLojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incluiProdutoLojaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaProdutosLoja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LojaProduto[] consultaProdutosLoja(int codLoja) {
            object[] results = this.Invoke("consultaProdutosLoja", new object[] {
                        codLoja});
            return ((LojaProduto[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaProdutosLojaAsync(int codLoja) {
            this.consultaProdutosLojaAsync(codLoja, null);
        }
        
        /// <remarks/>
        public void consultaProdutosLojaAsync(int codLoja, object userState) {
            if ((this.consultaProdutosLojaOperationCompleted == null)) {
                this.consultaProdutosLojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaProdutosLojaOperationCompleted);
            }
            this.InvokeAsync("consultaProdutosLoja", new object[] {
                        codLoja}, this.consultaProdutosLojaOperationCompleted, userState);
        }
        
        private void OnconsultaProdutosLojaOperationCompleted(object arg) {
            if ((this.consultaProdutosLojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaProdutosLojaCompleted(this, new consultaProdutosLojaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluiLojaProdutos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluiLojaProdutos(int codLoja, int codProd) {
            this.Invoke("excluiLojaProdutos", new object[] {
                        codLoja,
                        codProd});
        }
        
        /// <remarks/>
        public void excluiLojaProdutosAsync(int codLoja, int codProd) {
            this.excluiLojaProdutosAsync(codLoja, codProd, null);
        }
        
        /// <remarks/>
        public void excluiLojaProdutosAsync(int codLoja, int codProd, object userState) {
            if ((this.excluiLojaProdutosOperationCompleted == null)) {
                this.excluiLojaProdutosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluiLojaProdutosOperationCompleted);
            }
            this.InvokeAsync("excluiLojaProdutos", new object[] {
                        codLoja,
                        codProd}, this.excluiLojaProdutosOperationCompleted, userState);
        }
        
        private void OnexcluiLojaProdutosOperationCompleted(object arg) {
            if ((this.excluiLojaProdutosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluiLojaProdutosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alteraLojaProdutos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alteraLojaProdutos(int codLoja, int codProd, double preco) {
            this.Invoke("alteraLojaProdutos", new object[] {
                        codLoja,
                        codProd,
                        preco});
        }
        
        /// <remarks/>
        public void alteraLojaProdutosAsync(int codLoja, int codProd, double preco) {
            this.alteraLojaProdutosAsync(codLoja, codProd, preco, null);
        }
        
        /// <remarks/>
        public void alteraLojaProdutosAsync(int codLoja, int codProd, double preco, object userState) {
            if ((this.alteraLojaProdutosOperationCompleted == null)) {
                this.alteraLojaProdutosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraLojaProdutosOperationCompleted);
            }
            this.InvokeAsync("alteraLojaProdutos", new object[] {
                        codLoja,
                        codProd,
                        preco}, this.alteraLojaProdutosOperationCompleted, userState);
        }
        
        private void OnalteraLojaProdutosOperationCompleted(object arg) {
            if ((this.alteraLojaProdutosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraLojaProdutosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/realizaVenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void realizaVenda(vendas v) {
            this.Invoke("realizaVenda", new object[] {
                        v});
        }
        
        /// <remarks/>
        public void realizaVendaAsync(vendas v) {
            this.realizaVendaAsync(v, null);
        }
        
        /// <remarks/>
        public void realizaVendaAsync(vendas v, object userState) {
            if ((this.realizaVendaOperationCompleted == null)) {
                this.realizaVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrealizaVendaOperationCompleted);
            }
            this.InvokeAsync("realizaVenda", new object[] {
                        v}, this.realizaVendaOperationCompleted, userState);
        }
        
        private void OnrealizaVendaOperationCompleted(object arg) {
            if ((this.realizaVendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.realizaVendaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/refactorProdutoNovo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void refactorProdutoNovo(Produto p) {
            this.Invoke("refactorProdutoNovo", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void refactorProdutoNovoAsync(Produto p) {
            this.refactorProdutoNovoAsync(p, null);
        }
        
        /// <remarks/>
        public void refactorProdutoNovoAsync(Produto p, object userState) {
            if ((this.refactorProdutoNovoOperationCompleted == null)) {
                this.refactorProdutoNovoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrefactorProdutoNovoOperationCompleted);
            }
            this.InvokeAsync("refactorProdutoNovo", new object[] {
                        p}, this.refactorProdutoNovoOperationCompleted, userState);
        }
        
        private void OnrefactorProdutoNovoOperationCompleted(object arg) {
            if ((this.refactorProdutoNovoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.refactorProdutoNovoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Deposito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Deposito(tipoCaixa c, double v, categ cc) {
            this.Invoke("Deposito", new object[] {
                        c,
                        v,
                        cc});
        }
        
        /// <remarks/>
        public void DepositoAsync(tipoCaixa c, double v, categ cc) {
            this.DepositoAsync(c, v, cc, null);
        }
        
        /// <remarks/>
        public void DepositoAsync(tipoCaixa c, double v, categ cc, object userState) {
            if ((this.DepositoOperationCompleted == null)) {
                this.DepositoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDepositoOperationCompleted);
            }
            this.InvokeAsync("Deposito", new object[] {
                        c,
                        v,
                        cc}, this.DepositoOperationCompleted, userState);
        }
        
        private void OnDepositoOperationCompleted(object arg) {
            if ((this.DepositoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DepositoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Saque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Saque(tipoCaixa c, double v, categ cc) {
            this.Invoke("Saque", new object[] {
                        c,
                        v,
                        cc});
        }
        
        /// <remarks/>
        public void SaqueAsync(tipoCaixa c, double v, categ cc) {
            this.SaqueAsync(c, v, cc, null);
        }
        
        /// <remarks/>
        public void SaqueAsync(tipoCaixa c, double v, categ cc, object userState) {
            if ((this.SaqueOperationCompleted == null)) {
                this.SaqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaqueOperationCompleted);
            }
            this.InvokeAsync("Saque", new object[] {
                        c,
                        v,
                        cc}, this.SaqueOperationCompleted, userState);
        }
        
        private void OnSaqueOperationCompleted(object arg) {
            if ((this.SaqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaqueCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/incluiTipoCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void incluiTipoCaixa(string nome) {
            this.Invoke("incluiTipoCaixa", new object[] {
                        nome});
        }
        
        /// <remarks/>
        public void incluiTipoCaixaAsync(string nome) {
            this.incluiTipoCaixaAsync(nome, null);
        }
        
        /// <remarks/>
        public void incluiTipoCaixaAsync(string nome, object userState) {
            if ((this.incluiTipoCaixaOperationCompleted == null)) {
                this.incluiTipoCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincluiTipoCaixaOperationCompleted);
            }
            this.InvokeAsync("incluiTipoCaixa", new object[] {
                        nome}, this.incluiTipoCaixaOperationCompleted, userState);
        }
        
        private void OnincluiTipoCaixaOperationCompleted(object arg) {
            if ((this.incluiTipoCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incluiTipoCaixaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Saldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Saldo() {
            this.Invoke("Saldo", new object[0]);
        }
        
        /// <remarks/>
        public void SaldoAsync() {
            this.SaldoAsync(null);
        }
        
        /// <remarks/>
        public void SaldoAsync(object userState) {
            if ((this.SaldoOperationCompleted == null)) {
                this.SaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoOperationCompleted);
            }
            this.InvokeAsync("Saldo", new object[0], this.SaldoOperationCompleted, userState);
        }
        
        private void OnSaldoOperationCompleted(object arg) {
            if ((this.SaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saldoCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saldoCaixa(tipoCaixa c) {
            this.Invoke("saldoCaixa", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void saldoCaixaAsync(tipoCaixa c) {
            this.saldoCaixaAsync(c, null);
        }
        
        /// <remarks/>
        public void saldoCaixaAsync(tipoCaixa c, object userState) {
            if ((this.saldoCaixaOperationCompleted == null)) {
                this.saldoCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaldoCaixaOperationCompleted);
            }
            this.InvokeAsync("saldoCaixa", new object[] {
                        c}, this.saldoCaixaOperationCompleted, userState);
        }
        
        private void OnsaldoCaixaOperationCompleted(object arg) {
            if ((this.saldoCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saldoCaixaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/incluiTipoCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void incluiTipoCategoria(string nome) {
            this.Invoke("incluiTipoCategoria", new object[] {
                        nome});
        }
        
        /// <remarks/>
        public void incluiTipoCategoriaAsync(string nome) {
            this.incluiTipoCategoriaAsync(nome, null);
        }
        
        /// <remarks/>
        public void incluiTipoCategoriaAsync(string nome, object userState) {
            if ((this.incluiTipoCategoriaOperationCompleted == null)) {
                this.incluiTipoCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincluiTipoCategoriaOperationCompleted);
            }
            this.InvokeAsync("incluiTipoCategoria", new object[] {
                        nome}, this.incluiTipoCategoriaOperationCompleted, userState);
        }
        
        private void OnincluiTipoCategoriaOperationCompleted(object arg) {
            if ((this.incluiTipoCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incluiTipoCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/incluiCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void incluiCliente(Cliente cc) {
            this.Invoke("incluiCliente", new object[] {
                        cc});
        }
        
        /// <remarks/>
        public void incluiClienteAsync(Cliente cc) {
            this.incluiClienteAsync(cc, null);
        }
        
        /// <remarks/>
        public void incluiClienteAsync(Cliente cc, object userState) {
            if ((this.incluiClienteOperationCompleted == null)) {
                this.incluiClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincluiClienteOperationCompleted);
            }
            this.InvokeAsync("incluiCliente", new object[] {
                        cc}, this.incluiClienteOperationCompleted, userState);
        }
        
        private void OnincluiClienteOperationCompleted(object arg) {
            if ((this.incluiClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incluiClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alteraCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void alteraCliente(int cod_cliente, string email, string end, string nome, string tel) {
            this.Invoke("alteraCliente", new object[] {
                        cod_cliente,
                        email,
                        end,
                        nome,
                        tel});
        }
        
        /// <remarks/>
        public void alteraClienteAsync(int cod_cliente, string email, string end, string nome, string tel) {
            this.alteraClienteAsync(cod_cliente, email, end, nome, tel, null);
        }
        
        /// <remarks/>
        public void alteraClienteAsync(int cod_cliente, string email, string end, string nome, string tel, object userState) {
            if ((this.alteraClienteOperationCompleted == null)) {
                this.alteraClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalteraClienteOperationCompleted);
            }
            this.InvokeAsync("alteraCliente", new object[] {
                        cod_cliente,
                        email,
                        end,
                        nome,
                        tel}, this.alteraClienteOperationCompleted, userState);
        }
        
        private void OnalteraClienteOperationCompleted(object arg) {
            if ((this.alteraClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alteraClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluicliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluicliente(int cod_cliente) {
            this.Invoke("excluicliente", new object[] {
                        cod_cliente});
        }
        
        /// <remarks/>
        public void excluiclienteAsync(int cod_cliente) {
            this.excluiclienteAsync(cod_cliente, null);
        }
        
        /// <remarks/>
        public void excluiclienteAsync(int cod_cliente, object userState) {
            if ((this.excluiclienteOperationCompleted == null)) {
                this.excluiclienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluiclienteOperationCompleted);
            }
            this.InvokeAsync("excluicliente", new object[] {
                        cod_cliente}, this.excluiclienteOperationCompleted, userState);
        }
        
        private void OnexcluiclienteOperationCompleted(object arg) {
            if ((this.excluiclienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluiclienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public cliente consultaCliente(int cod_cliente) {
            object[] results = this.Invoke("consultaCliente", new object[] {
                        cod_cliente});
            return ((cliente)(results[0]));
        }
        
        /// <remarks/>
        public void consultaClienteAsync(int cod_cliente) {
            this.consultaClienteAsync(cod_cliente, null);
        }
        
        /// <remarks/>
        public void consultaClienteAsync(int cod_cliente, object userState) {
            if ((this.consultaClienteOperationCompleted == null)) {
                this.consultaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaClienteOperationCompleted);
            }
            this.InvokeAsync("consultaCliente", new object[] {
                        cod_cliente}, this.consultaClienteOperationCompleted, userState);
        }
        
        private void OnconsultaClienteOperationCompleted(object arg) {
            if ((this.consultaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaClienteCompleted(this, new consultaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaTodosCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public cliente[] consultaTodosCliente() {
            object[] results = this.Invoke("consultaTodosCliente", new object[0]);
            return ((cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaTodosClienteAsync() {
            this.consultaTodosClienteAsync(null);
        }
        
        /// <remarks/>
        public void consultaTodosClienteAsync(object userState) {
            if ((this.consultaTodosClienteOperationCompleted == null)) {
                this.consultaTodosClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaTodosClienteOperationCompleted);
            }
            this.InvokeAsync("consultaTodosCliente", new object[0], this.consultaTodosClienteOperationCompleted, userState);
        }
        
        private void OnconsultaTodosClienteOperationCompleted(object arg) {
            if ((this.consultaTodosClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaTodosClienteCompleted(this, new consultaTodosClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class produto : EntityObject {
        
        private int cod_produtoField;
        
        private string nomeField;
        
        private System.Nullable<int> quantidadeField;
        
        private string cod_produto_MLField;
        
        /// <remarks/>
        public int cod_produto {
            get {
                return this.cod_produtoField;
            }
            set {
                this.cod_produtoField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string cod_produto_ML {
            get {
                return this.cod_produto_MLField;
            }
            set {
                this.cod_produto_MLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LojaProduto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Loja))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(produto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private string _emailField;
        
        private string _enderecoField;
        
        private string _nomeField;
        
        private string _telefoneField;
        
        private string _cod_cliente_MLField;
        
        private int _cod_clienteField;
        
        /// <remarks/>
        public string _email {
            get {
                return this._emailField;
            }
            set {
                this._emailField = value;
            }
        }
        
        /// <remarks/>
        public string _endereco {
            get {
                return this._enderecoField;
            }
            set {
                this._enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string _nome {
            get {
                return this._nomeField;
            }
            set {
                this._nomeField = value;
            }
        }
        
        /// <remarks/>
        public string _telefone {
            get {
                return this._telefoneField;
            }
            set {
                this._telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string _cod_cliente_ML {
            get {
                return this._cod_cliente_MLField;
            }
            set {
                this._cod_cliente_MLField = value;
            }
        }
        
        /// <remarks/>
        public int _cod_cliente {
            get {
                return this._cod_clienteField;
            }
            set {
                this._cod_clienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tipoLoja {
        
        private string nomeField;
        
        private decimal tarifaField;
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Produto {
        
        private int idField;
        
        private string nomeField;
        
        private double precoField;
        
        private tipoLoja[] lojaField;
        
        private int qtdField;
        
        private string id_MLField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public double preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public tipoLoja[] loja {
            get {
                return this.lojaField;
            }
            set {
                this.lojaField = value;
            }
        }
        
        /// <remarks/>
        public int qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
            }
        }
        
        /// <remarks/>
        public string id_ML {
            get {
                return this.id_MLField;
            }
            set {
                this.id_MLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vendas {
        
        private int cod_itemField;
        
        private int cod_vendaField;
        
        private int qtdField;
        
        private System.DateTime dataField;
        
        private Produto prodField;
        
        private System.Nullable<System.DateTime> data_pagtoField;
        
        private Cliente cliField;
        
        /// <remarks/>
        public int cod_item {
            get {
                return this.cod_itemField;
            }
            set {
                this.cod_itemField = value;
            }
        }
        
        /// <remarks/>
        public int cod_venda {
            get {
                return this.cod_vendaField;
            }
            set {
                this.cod_vendaField = value;
            }
        }
        
        /// <remarks/>
        public int qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Produto prod {
            get {
                return this.prodField;
            }
            set {
                this.prodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> data_pagto {
            get {
                return this.data_pagtoField;
            }
            set {
                this.data_pagtoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente cli {
            get {
                return this.cliField;
            }
            set {
                this.cliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfproduto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoja))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfproduto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLoja))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfproduto : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfLoja : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LojaProduto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Loja))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(produto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cliente : EntityObject {
        
        private int cod_clienteField;
        
        private string nomeField;
        
        private string emailField;
        
        private string telefoneField;
        
        private string enderecoField;
        
        private string cod_cliente_MLField;
        
        /// <remarks/>
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                this.cod_clienteField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string cod_cliente_ML {
            get {
                return this.cod_cliente_MLField;
            }
            set {
                this.cod_cliente_MLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LojaProduto : EntityObject {
        
        private int cod_ProdutoField;
        
        private int cod_LojaField;
        
        private double precoField;
        
        private EntityReferenceOfproduto produtoReferenceField;
        
        private EntityReferenceOfLoja lojaReferenceField;
        
        /// <remarks/>
        public int Cod_Produto {
            get {
                return this.cod_ProdutoField;
            }
            set {
                this.cod_ProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_Loja {
            get {
                return this.cod_LojaField;
            }
            set {
                this.cod_LojaField = value;
            }
        }
        
        /// <remarks/>
        public double Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfproduto produtoReference {
            get {
                return this.produtoReferenceField;
            }
            set {
                this.produtoReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLoja LojaReference {
            get {
                return this.lojaReferenceField;
            }
            set {
                this.lojaReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Loja : EntityObject {
        
        private int cod_LojaField;
        
        private string nomeField;
        
        private System.Nullable<double> tarifaField;
        
        /// <remarks/>
        public int Cod_Loja {
            get {
                return this.cod_LojaField;
            }
            set {
                this.cod_LojaField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum tipoCaixa {
        
        /// <remarks/>
        Tiago,
        
        /// <remarks/>
        Ricardo,
        
        /// <remarks/>
        NerdSa,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum categ {
        
        /// <remarks/>
        Correios,
        
        /// <remarks/>
        Papelaria,
        
        /// <remarks/>
        Transporte,
        
        /// <remarks/>
        Prejuizo,
        
        /// <remarks/>
        VendaProduto,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaTodosProdutosCompletedEventHandler(object sender, consultaTodosProdutosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaTodosProdutosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaTodosProdutosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public produto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((produto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaProdutoCompletedEventHandler(object sender, consultaProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public produto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((produto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void alteraProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void excluiProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void incluiLojaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaLojaCompletedEventHandler(object sender, consultaLojaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaLojaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaLojaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Loja[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Loja[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaTodasLojasCompletedEventHandler(object sender, consultaTodasLojasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaTodasLojasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaTodasLojasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Loja[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Loja[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void alteraLojaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void excluiLojasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void incluiProdutoLojaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaProdutosLojaCompletedEventHandler(object sender, consultaProdutosLojaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaProdutosLojaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaProdutosLojaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LojaProduto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LojaProduto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void excluiLojaProdutosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void alteraLojaProdutosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void realizaVendaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void refactorProdutoNovoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DepositoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaqueCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void incluiTipoCaixaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaldoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void saldoCaixaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void incluiTipoCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void incluiClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void alteraClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void excluiclienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaClienteCompletedEventHandler(object sender, consultaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void consultaTodosClienteCompletedEventHandler(object sender, consultaTodosClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaTodosClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaTodosClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cliente[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591